// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

public interface annotationsTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burpApi.annotationsText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 是否有注解信息
   * </pre>
   *
   * <code>bool isInfo = 1;</code>
   * @return The isInfo.
   */
  boolean getIsInfo();

  /**
   * <pre>
   * 注解文本
   * </pre>
   *
   * <code>string notes = 2;</code>
   * @return The notes.
   */
  java.lang.String getNotes();
  /**
   * <pre>
   * 注解文本
   * </pre>
   *
   * <code>string notes = 2;</code>
   * @return The bytes for notes.
   */
  com.google.protobuf.ByteString
      getNotesBytes();

  /**
   * <pre>
   * 颜色
   * </pre>
   *
   * <code>string color = 3;</code>
   * @return The color.
   */
  java.lang.String getColor();
  /**
   * <pre>
   * 颜色
   * </pre>
   *
   * <code>string color = 3;</code>
   * @return The bytes for color.
   */
  com.google.protobuf.ByteString
      getColorBytes();
}
