// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

public interface BooleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burpApi.Boole)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool boole = 1;</code>
   * @return The boole.
   */
  boolean getBoole();
}
