// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

public interface ByteDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burpApi.ByteData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes byteData = 1;</code>
   * @return The byteData.
   */
  com.google.protobuf.ByteString getByteData();
}
