// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 上下文处理器 , 提供 一组请求响应 和选中的数据
 * </pre>
 *
 * Protobuf type {@code burpApi.ContextMenuItems}
 */
public final class ContextMenuItems extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:burpApi.ContextMenuItems)
    ContextMenuItemsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContextMenuItems.newBuilder() to construct.
  private ContextMenuItems(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContextMenuItems() {
    name_ = "";
    selectData_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContextMenuItems();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ContextMenuItems_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ContextMenuItems_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.ContextMenuItems.class, BurpGrpc.proto.BurpApiGrpc.ContextMenuItems.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   *名称
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *名称
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSELECT_FIELD_NUMBER = 4;
  private boolean isSelect_ = false;
  /**
   * <pre>
   * 是否有选中的数据
   * </pre>
   *
   * <code>bool isSelect = 4;</code>
   * @return The isSelect.
   */
  @java.lang.Override
  public boolean getIsSelect() {
    return isSelect_;
  }

  public static final int HTTPREQANDRES_FIELD_NUMBER = 1;
  private BurpGrpc.proto.BurpApiGrpc.httpReqAndRes httpReqAndRes_;
  /**
   * <pre>
   * 一组请求和响应
   * </pre>
   *
   * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
   * @return Whether the httpReqAndRes field is set.
   */
  @java.lang.Override
  public boolean hasHttpReqAndRes() {
    return httpReqAndRes_ != null;
  }
  /**
   * <pre>
   * 一组请求和响应
   * </pre>
   *
   * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
   * @return The httpReqAndRes.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpReqAndRes getHttpReqAndRes() {
    return httpReqAndRes_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.getDefaultInstance() : httpReqAndRes_;
  }
  /**
   * <pre>
   * 一组请求和响应
   * </pre>
   *
   * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpReqAndResOrBuilder getHttpReqAndResOrBuilder() {
    return httpReqAndRes_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.getDefaultInstance() : httpReqAndRes_;
  }

  public static final int SELECTDATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString selectData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 用户选中的数据
   * </pre>
   *
   * <code>bytes selectData = 2;</code>
   * @return The selectData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSelectData() {
    return selectData_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (httpReqAndRes_ != null) {
      output.writeMessage(1, getHttpReqAndRes());
    }
    if (!selectData_.isEmpty()) {
      output.writeBytes(2, selectData_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (isSelect_ != false) {
      output.writeBool(4, isSelect_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (httpReqAndRes_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHttpReqAndRes());
    }
    if (!selectData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, selectData_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (isSelect_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isSelect_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.ContextMenuItems)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.ContextMenuItems other = (BurpGrpc.proto.BurpApiGrpc.ContextMenuItems) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getIsSelect()
        != other.getIsSelect()) return false;
    if (hasHttpReqAndRes() != other.hasHttpReqAndRes()) return false;
    if (hasHttpReqAndRes()) {
      if (!getHttpReqAndRes()
          .equals(other.getHttpReqAndRes())) return false;
    }
    if (!getSelectData()
        .equals(other.getSelectData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ISSELECT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSelect());
    if (hasHttpReqAndRes()) {
      hash = (37 * hash) + HTTPREQANDRES_FIELD_NUMBER;
      hash = (53 * hash) + getHttpReqAndRes().hashCode();
    }
    hash = (37 * hash) + SELECTDATA_FIELD_NUMBER;
    hash = (53 * hash) + getSelectData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.ContextMenuItems prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 上下文处理器 , 提供 一组请求响应 和选中的数据
   * </pre>
   *
   * Protobuf type {@code burpApi.ContextMenuItems}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:burpApi.ContextMenuItems)
      BurpGrpc.proto.BurpApiGrpc.ContextMenuItemsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ContextMenuItems_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ContextMenuItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.ContextMenuItems.class, BurpGrpc.proto.BurpApiGrpc.ContextMenuItems.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.ContextMenuItems.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      isSelect_ = false;
      httpReqAndRes_ = null;
      if (httpReqAndResBuilder_ != null) {
        httpReqAndResBuilder_.dispose();
        httpReqAndResBuilder_ = null;
      }
      selectData_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ContextMenuItems_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ContextMenuItems getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.ContextMenuItems.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ContextMenuItems build() {
      BurpGrpc.proto.BurpApiGrpc.ContextMenuItems result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ContextMenuItems buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.ContextMenuItems result = new BurpGrpc.proto.BurpApiGrpc.ContextMenuItems(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.ContextMenuItems result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isSelect_ = isSelect_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.httpReqAndRes_ = httpReqAndResBuilder_ == null
            ? httpReqAndRes_
            : httpReqAndResBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.selectData_ = selectData_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.ContextMenuItems) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.ContextMenuItems)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.ContextMenuItems other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.ContextMenuItems.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIsSelect() != false) {
        setIsSelect(other.getIsSelect());
      }
      if (other.hasHttpReqAndRes()) {
        mergeHttpReqAndRes(other.getHttpReqAndRes());
      }
      if (other.getSelectData() != com.google.protobuf.ByteString.EMPTY) {
        setSelectData(other.getSelectData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHttpReqAndResFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 10
            case 18: {
              selectData_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 18
            case 26: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 26
            case 32: {
              isSelect_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *名称
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean isSelect_ ;
    /**
     * <pre>
     * 是否有选中的数据
     * </pre>
     *
     * <code>bool isSelect = 4;</code>
     * @return The isSelect.
     */
    @java.lang.Override
    public boolean getIsSelect() {
      return isSelect_;
    }
    /**
     * <pre>
     * 是否有选中的数据
     * </pre>
     *
     * <code>bool isSelect = 4;</code>
     * @param value The isSelect to set.
     * @return This builder for chaining.
     */
    public Builder setIsSelect(boolean value) {

      isSelect_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否有选中的数据
     * </pre>
     *
     * <code>bool isSelect = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSelect() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isSelect_ = false;
      onChanged();
      return this;
    }

    private BurpGrpc.proto.BurpApiGrpc.httpReqAndRes httpReqAndRes_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpReqAndRes, BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqAndResOrBuilder> httpReqAndResBuilder_;
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     * @return Whether the httpReqAndRes field is set.
     */
    public boolean hasHttpReqAndRes() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     * @return The httpReqAndRes.
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqAndRes getHttpReqAndRes() {
      if (httpReqAndResBuilder_ == null) {
        return httpReqAndRes_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.getDefaultInstance() : httpReqAndRes_;
      } else {
        return httpReqAndResBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     */
    public Builder setHttpReqAndRes(BurpGrpc.proto.BurpApiGrpc.httpReqAndRes value) {
      if (httpReqAndResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        httpReqAndRes_ = value;
      } else {
        httpReqAndResBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     */
    public Builder setHttpReqAndRes(
        BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.Builder builderForValue) {
      if (httpReqAndResBuilder_ == null) {
        httpReqAndRes_ = builderForValue.build();
      } else {
        httpReqAndResBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     */
    public Builder mergeHttpReqAndRes(BurpGrpc.proto.BurpApiGrpc.httpReqAndRes value) {
      if (httpReqAndResBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          httpReqAndRes_ != null &&
          httpReqAndRes_ != BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.getDefaultInstance()) {
          getHttpReqAndResBuilder().mergeFrom(value);
        } else {
          httpReqAndRes_ = value;
        }
      } else {
        httpReqAndResBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     */
    public Builder clearHttpReqAndRes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      httpReqAndRes_ = null;
      if (httpReqAndResBuilder_ != null) {
        httpReqAndResBuilder_.dispose();
        httpReqAndResBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.Builder getHttpReqAndResBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getHttpReqAndResFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqAndResOrBuilder getHttpReqAndResOrBuilder() {
      if (httpReqAndResBuilder_ != null) {
        return httpReqAndResBuilder_.getMessageOrBuilder();
      } else {
        return httpReqAndRes_ == null ?
            BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.getDefaultInstance() : httpReqAndRes_;
      }
    }
    /**
     * <pre>
     * 一组请求和响应
     * </pre>
     *
     * <code>.burpApi.httpReqAndRes httpReqAndRes = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpReqAndRes, BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqAndResOrBuilder> 
        getHttpReqAndResFieldBuilder() {
      if (httpReqAndResBuilder_ == null) {
        httpReqAndResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.httpReqAndRes, BurpGrpc.proto.BurpApiGrpc.httpReqAndRes.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqAndResOrBuilder>(
                getHttpReqAndRes(),
                getParentForChildren(),
                isClean());
        httpReqAndRes_ = null;
      }
      return httpReqAndResBuilder_;
    }

    private com.google.protobuf.ByteString selectData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 用户选中的数据
     * </pre>
     *
     * <code>bytes selectData = 2;</code>
     * @return The selectData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSelectData() {
      return selectData_;
    }
    /**
     * <pre>
     * 用户选中的数据
     * </pre>
     *
     * <code>bytes selectData = 2;</code>
     * @param value The selectData to set.
     * @return This builder for chaining.
     */
    public Builder setSelectData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      selectData_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户选中的数据
     * </pre>
     *
     * <code>bytes selectData = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      selectData_ = getDefaultInstance().getSelectData();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:burpApi.ContextMenuItems)
  }

  // @@protoc_insertion_point(class_scope:burpApi.ContextMenuItems)
  private static final BurpGrpc.proto.BurpApiGrpc.ContextMenuItems DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.ContextMenuItems();
  }

  public static BurpGrpc.proto.BurpApiGrpc.ContextMenuItems getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContextMenuItems>
      PARSER = new com.google.protobuf.AbstractParser<ContextMenuItems>() {
    @java.lang.Override
    public ContextMenuItems parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContextMenuItems> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContextMenuItems> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.ContextMenuItems getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

