// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

public interface httpResGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burpApi.httpResGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.burpApi.httpResData httpResData = 1;</code>
   * @return Whether the httpResData field is set.
   */
  boolean hasHttpResData();
  /**
   * <code>.burpApi.httpResData httpResData = 1;</code>
   * @return The httpResData.
   */
  BurpGrpc.proto.BurpApiGrpc.httpResData getHttpResData();
  /**
   * <code>.burpApi.httpResData httpResData = 1;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder getHttpResDataOrBuilder();

  /**
   * <code>.burpApi.annotationsText annotationsText = 2;</code>
   * @return Whether the annotationsText field is set.
   */
  boolean hasAnnotationsText();
  /**
   * <code>.burpApi.annotationsText annotationsText = 2;</code>
   * @return The annotationsText.
   */
  BurpGrpc.proto.BurpApiGrpc.annotationsText getAnnotationsText();
  /**
   * <code>.burpApi.annotationsText annotationsText = 2;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.annotationsTextOrBuilder getAnnotationsTextOrBuilder();
}
