// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface httpFlowReqDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.httpFlowReqData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BurpMorePossibilityApi.httpReqGroup httpReqGroup = 1;</code>
   * @return Whether the httpReqGroup field is set.
   */
  boolean hasHttpReqGroup();
  /**
   * <code>.BurpMorePossibilityApi.httpReqGroup httpReqGroup = 1;</code>
   * @return The httpReqGroup.
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqGroup getHttpReqGroup();
  /**
   * <code>.BurpMorePossibilityApi.httpReqGroup httpReqGroup = 1;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder getHttpReqGroupOrBuilder();

  /**
   * <code>.BurpMorePossibilityApi.httpFlowSource httpFlowSource = 2;</code>
   * @return The enum numeric value on the wire for httpFlowSource.
   */
  int getHttpFlowSourceValue();
  /**
   * <code>.BurpMorePossibilityApi.httpFlowSource httpFlowSource = 2;</code>
   * @return The httpFlowSource.
   */
  BurpGrpc.proto.BurpApiGrpc.httpFlowSource getHttpFlowSource();
}
