// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

public interface HttpRequestActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burpApi.HttpRequestAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 继续不做任何处理
   * </pre>
   *
   * <code>bool continue = 1;</code>
   * @return The continue.
   */
  boolean getContinue();

  /**
   * <pre>
   * 修改请求
   * </pre>
   *
   * <code>bool isReviseReq = 3;</code>
   * @return The isReviseReq.
   */
  boolean getIsReviseReq();

  /**
   * <code>.burpApi.httpReqGroup httpReqGroup = 4;</code>
   * @return Whether the httpReqGroup field is set.
   */
  boolean hasHttpReqGroup();
  /**
   * <code>.burpApi.httpReqGroup httpReqGroup = 4;</code>
   * @return The httpReqGroup.
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqGroup getHttpReqGroup();
  /**
   * <code>.burpApi.httpReqGroup httpReqGroup = 4;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder getHttpReqGroupOrBuilder();
}
