// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 流量来源类型
 * </pre>
 *
 * Protobuf enum {@code burpApi.httpFlowSource}
 */
public enum httpFlowSource
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 空值占位表示null 避免不同语言序列化后无法判断对象是否为空
   * </pre>
   *
   * <code>NULL = 0;</code>
   */
  NULL(0),
  /**
   * <code>SUITE = 1;</code>
   */
  SUITE(1),
  /**
   * <code>TARGET = 2;</code>
   */
  TARGET(2),
  /**
   * <pre>
   * 代理器
   * </pre>
   *
   * <code>PROXY = 3;</code>
   */
  PROXY(3),
  /**
   * <code>SCANNER = 4;</code>
   */
  SCANNER(4),
  /**
   * <pre>
   * 迭代器
   * </pre>
   *
   * <code>INTRUDER = 5;</code>
   */
  INTRUDER(5),
  /**
   * <pre>
   * 重放器
   * </pre>
   *
   * <code>REPEATER = 6;</code>
   */
  REPEATER(6),
  /**
   * <code>LOGGER = 7;</code>
   */
  LOGGER(7),
  /**
   * <code>SEQUENCER = 8;</code>
   */
  SEQUENCER(8),
  /**
   * <code>DECODER = 9;</code>
   */
  DECODER(9),
  /**
   * <code>COMPARER = 10;</code>
   */
  COMPARER(10),
  /**
   * <code>EXTENSIONS = 11;</code>
   */
  EXTENSIONS(11),
  /**
   * <code>RECORDED_LOGIN_REPLAYER = 12;</code>
   */
  RECORDED_LOGIN_REPLAYER(12),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 空值占位表示null 避免不同语言序列化后无法判断对象是否为空
   * </pre>
   *
   * <code>NULL = 0;</code>
   */
  public static final int NULL_VALUE = 0;
  /**
   * <code>SUITE = 1;</code>
   */
  public static final int SUITE_VALUE = 1;
  /**
   * <code>TARGET = 2;</code>
   */
  public static final int TARGET_VALUE = 2;
  /**
   * <pre>
   * 代理器
   * </pre>
   *
   * <code>PROXY = 3;</code>
   */
  public static final int PROXY_VALUE = 3;
  /**
   * <code>SCANNER = 4;</code>
   */
  public static final int SCANNER_VALUE = 4;
  /**
   * <pre>
   * 迭代器
   * </pre>
   *
   * <code>INTRUDER = 5;</code>
   */
  public static final int INTRUDER_VALUE = 5;
  /**
   * <pre>
   * 重放器
   * </pre>
   *
   * <code>REPEATER = 6;</code>
   */
  public static final int REPEATER_VALUE = 6;
  /**
   * <code>LOGGER = 7;</code>
   */
  public static final int LOGGER_VALUE = 7;
  /**
   * <code>SEQUENCER = 8;</code>
   */
  public static final int SEQUENCER_VALUE = 8;
  /**
   * <code>DECODER = 9;</code>
   */
  public static final int DECODER_VALUE = 9;
  /**
   * <code>COMPARER = 10;</code>
   */
  public static final int COMPARER_VALUE = 10;
  /**
   * <code>EXTENSIONS = 11;</code>
   */
  public static final int EXTENSIONS_VALUE = 11;
  /**
   * <code>RECORDED_LOGIN_REPLAYER = 12;</code>
   */
  public static final int RECORDED_LOGIN_REPLAYER_VALUE = 12;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static httpFlowSource valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static httpFlowSource forNumber(int value) {
    switch (value) {
      case 0: return NULL;
      case 1: return SUITE;
      case 2: return TARGET;
      case 3: return PROXY;
      case 4: return SCANNER;
      case 5: return INTRUDER;
      case 6: return REPEATER;
      case 7: return LOGGER;
      case 8: return SEQUENCER;
      case 9: return DECODER;
      case 10: return COMPARER;
      case 11: return EXTENSIONS;
      case 12: return RECORDED_LOGIN_REPLAYER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<httpFlowSource>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      httpFlowSource> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<httpFlowSource>() {
          public httpFlowSource findValueByNumber(int number) {
            return httpFlowSource.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.getDescriptor().getEnumTypes().get(1);
  }

  private static final httpFlowSource[] VALUES = values();

  public static httpFlowSource valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private httpFlowSource(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:burpApi.httpFlowSource)
}

