// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * http 单个响应组 用于包含 不同服务响应中的附带信息
 * </pre>
 *
 * Protobuf type {@code BurpMorePossibilityApi.httpResGroup}
 */
public final class httpResGroup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BurpMorePossibilityApi.httpResGroup)
    httpResGroupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use httpResGroup.newBuilder() to construct.
  private httpResGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private httpResGroup() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new httpResGroup();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_httpResGroup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_httpResGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.httpResGroup.class, BurpGrpc.proto.BurpApiGrpc.httpResGroup.Builder.class);
  }

  private int bitField0_;
  public static final int HTTPRESDATA_FIELD_NUMBER = 1;
  private BurpGrpc.proto.BurpApiGrpc.httpResData httpResData_;
  /**
   * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
   * @return Whether the httpResData field is set.
   */
  @java.lang.Override
  public boolean hasHttpResData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
   * @return The httpResData.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpResData getHttpResData() {
    return httpResData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : httpResData_;
  }
  /**
   * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder getHttpResDataOrBuilder() {
    return httpResData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : httpResData_;
  }

  public static final int ANNOTATIONSTEXT_FIELD_NUMBER = 2;
  private BurpGrpc.proto.BurpApiGrpc.annotationsText annotationsText_;
  /**
   * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
   * @return Whether the annotationsText field is set.
   */
  @java.lang.Override
  public boolean hasAnnotationsText() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
   * @return The annotationsText.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.annotationsText getAnnotationsText() {
    return annotationsText_ == null ? BurpGrpc.proto.BurpApiGrpc.annotationsText.getDefaultInstance() : annotationsText_;
  }
  /**
   * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.annotationsTextOrBuilder getAnnotationsTextOrBuilder() {
    return annotationsText_ == null ? BurpGrpc.proto.BurpApiGrpc.annotationsText.getDefaultInstance() : annotationsText_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getHttpResData());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getAnnotationsText());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHttpResData());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAnnotationsText());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.httpResGroup)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.httpResGroup other = (BurpGrpc.proto.BurpApiGrpc.httpResGroup) obj;

    if (hasHttpResData() != other.hasHttpResData()) return false;
    if (hasHttpResData()) {
      if (!getHttpResData()
          .equals(other.getHttpResData())) return false;
    }
    if (hasAnnotationsText() != other.hasAnnotationsText()) return false;
    if (hasAnnotationsText()) {
      if (!getAnnotationsText()
          .equals(other.getAnnotationsText())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHttpResData()) {
      hash = (37 * hash) + HTTPRESDATA_FIELD_NUMBER;
      hash = (53 * hash) + getHttpResData().hashCode();
    }
    if (hasAnnotationsText()) {
      hash = (37 * hash) + ANNOTATIONSTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getAnnotationsText().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.httpResGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * http 单个响应组 用于包含 不同服务响应中的附带信息
   * </pre>
   *
   * Protobuf type {@code BurpMorePossibilityApi.httpResGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BurpMorePossibilityApi.httpResGroup)
      BurpGrpc.proto.BurpApiGrpc.httpResGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_httpResGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_httpResGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.httpResGroup.class, BurpGrpc.proto.BurpApiGrpc.httpResGroup.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.httpResGroup.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHttpResDataFieldBuilder();
        getAnnotationsTextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      httpResData_ = null;
      if (httpResDataBuilder_ != null) {
        httpResDataBuilder_.dispose();
        httpResDataBuilder_ = null;
      }
      annotationsText_ = null;
      if (annotationsTextBuilder_ != null) {
        annotationsTextBuilder_.dispose();
        annotationsTextBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_httpResGroup_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.httpResGroup getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.httpResGroup.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.httpResGroup build() {
      BurpGrpc.proto.BurpApiGrpc.httpResGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.httpResGroup buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.httpResGroup result = new BurpGrpc.proto.BurpApiGrpc.httpResGroup(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.httpResGroup result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.httpResData_ = httpResDataBuilder_ == null
            ? httpResData_
            : httpResDataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.annotationsText_ = annotationsTextBuilder_ == null
            ? annotationsText_
            : annotationsTextBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.httpResGroup) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.httpResGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.httpResGroup other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.httpResGroup.getDefaultInstance()) return this;
      if (other.hasHttpResData()) {
        mergeHttpResData(other.getHttpResData());
      }
      if (other.hasAnnotationsText()) {
        mergeAnnotationsText(other.getAnnotationsText());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHttpResDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAnnotationsTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private BurpGrpc.proto.BurpApiGrpc.httpResData httpResData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpResData, BurpGrpc.proto.BurpApiGrpc.httpResData.Builder, BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder> httpResDataBuilder_;
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     * @return Whether the httpResData field is set.
     */
    public boolean hasHttpResData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     * @return The httpResData.
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResData getHttpResData() {
      if (httpResDataBuilder_ == null) {
        return httpResData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : httpResData_;
      } else {
        return httpResDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     */
    public Builder setHttpResData(BurpGrpc.proto.BurpApiGrpc.httpResData value) {
      if (httpResDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        httpResData_ = value;
      } else {
        httpResDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     */
    public Builder setHttpResData(
        BurpGrpc.proto.BurpApiGrpc.httpResData.Builder builderForValue) {
      if (httpResDataBuilder_ == null) {
        httpResData_ = builderForValue.build();
      } else {
        httpResDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     */
    public Builder mergeHttpResData(BurpGrpc.proto.BurpApiGrpc.httpResData value) {
      if (httpResDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          httpResData_ != null &&
          httpResData_ != BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance()) {
          getHttpResDataBuilder().mergeFrom(value);
        } else {
          httpResData_ = value;
        }
      } else {
        httpResDataBuilder_.mergeFrom(value);
      }
      if (httpResData_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     */
    public Builder clearHttpResData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      httpResData_ = null;
      if (httpResDataBuilder_ != null) {
        httpResDataBuilder_.dispose();
        httpResDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResData.Builder getHttpResDataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHttpResDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder getHttpResDataOrBuilder() {
      if (httpResDataBuilder_ != null) {
        return httpResDataBuilder_.getMessageOrBuilder();
      } else {
        return httpResData_ == null ?
            BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : httpResData_;
      }
    }
    /**
     * <code>.BurpMorePossibilityApi.httpResData httpResData = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpResData, BurpGrpc.proto.BurpApiGrpc.httpResData.Builder, BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder> 
        getHttpResDataFieldBuilder() {
      if (httpResDataBuilder_ == null) {
        httpResDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.httpResData, BurpGrpc.proto.BurpApiGrpc.httpResData.Builder, BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder>(
                getHttpResData(),
                getParentForChildren(),
                isClean());
        httpResData_ = null;
      }
      return httpResDataBuilder_;
    }

    private BurpGrpc.proto.BurpApiGrpc.annotationsText annotationsText_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.annotationsText, BurpGrpc.proto.BurpApiGrpc.annotationsText.Builder, BurpGrpc.proto.BurpApiGrpc.annotationsTextOrBuilder> annotationsTextBuilder_;
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     * @return Whether the annotationsText field is set.
     */
    public boolean hasAnnotationsText() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     * @return The annotationsText.
     */
    public BurpGrpc.proto.BurpApiGrpc.annotationsText getAnnotationsText() {
      if (annotationsTextBuilder_ == null) {
        return annotationsText_ == null ? BurpGrpc.proto.BurpApiGrpc.annotationsText.getDefaultInstance() : annotationsText_;
      } else {
        return annotationsTextBuilder_.getMessage();
      }
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     */
    public Builder setAnnotationsText(BurpGrpc.proto.BurpApiGrpc.annotationsText value) {
      if (annotationsTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        annotationsText_ = value;
      } else {
        annotationsTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     */
    public Builder setAnnotationsText(
        BurpGrpc.proto.BurpApiGrpc.annotationsText.Builder builderForValue) {
      if (annotationsTextBuilder_ == null) {
        annotationsText_ = builderForValue.build();
      } else {
        annotationsTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     */
    public Builder mergeAnnotationsText(BurpGrpc.proto.BurpApiGrpc.annotationsText value) {
      if (annotationsTextBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          annotationsText_ != null &&
          annotationsText_ != BurpGrpc.proto.BurpApiGrpc.annotationsText.getDefaultInstance()) {
          getAnnotationsTextBuilder().mergeFrom(value);
        } else {
          annotationsText_ = value;
        }
      } else {
        annotationsTextBuilder_.mergeFrom(value);
      }
      if (annotationsText_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     */
    public Builder clearAnnotationsText() {
      bitField0_ = (bitField0_ & ~0x00000002);
      annotationsText_ = null;
      if (annotationsTextBuilder_ != null) {
        annotationsTextBuilder_.dispose();
        annotationsTextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.annotationsText.Builder getAnnotationsTextBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getAnnotationsTextFieldBuilder().getBuilder();
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.annotationsTextOrBuilder getAnnotationsTextOrBuilder() {
      if (annotationsTextBuilder_ != null) {
        return annotationsTextBuilder_.getMessageOrBuilder();
      } else {
        return annotationsText_ == null ?
            BurpGrpc.proto.BurpApiGrpc.annotationsText.getDefaultInstance() : annotationsText_;
      }
    }
    /**
     * <code>.BurpMorePossibilityApi.annotationsText annotationsText = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.annotationsText, BurpGrpc.proto.BurpApiGrpc.annotationsText.Builder, BurpGrpc.proto.BurpApiGrpc.annotationsTextOrBuilder> 
        getAnnotationsTextFieldBuilder() {
      if (annotationsTextBuilder_ == null) {
        annotationsTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.annotationsText, BurpGrpc.proto.BurpApiGrpc.annotationsText.Builder, BurpGrpc.proto.BurpApiGrpc.annotationsTextOrBuilder>(
                getAnnotationsText(),
                getParentForChildren(),
                isClean());
        annotationsText_ = null;
      }
      return annotationsTextBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BurpMorePossibilityApi.httpResGroup)
  }

  // @@protoc_insertion_point(class_scope:BurpMorePossibilityApi.httpResGroup)
  private static final BurpGrpc.proto.BurpApiGrpc.httpResGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.httpResGroup();
  }

  public static BurpGrpc.proto.BurpApiGrpc.httpResGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<httpResGroup>
      PARSER = new com.google.protobuf.AbstractParser<httpResGroup>() {
    @java.lang.Override
    public httpResGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<httpResGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<httpResGroup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpResGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

