// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface HttpResponseActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.HttpResponseAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 继续不做任何处理
   * </pre>
   *
   * <code>bool continue = 1;</code>
   * @return The continue.
   */
  boolean getContinue();

  /**
   * <pre>
   * 修改响应
   * </pre>
   *
   * <code>bool isReviseRes = 3;</code>
   * @return The isReviseRes.
   */
  boolean getIsReviseRes();

  /**
   * <code>.BurpMorePossibilityApi.httpResGroup httpResGroup = 4;</code>
   * @return Whether the httpResGroup field is set.
   */
  boolean hasHttpResGroup();
  /**
   * <code>.BurpMorePossibilityApi.httpResGroup httpResGroup = 4;</code>
   * @return The httpResGroup.
   */
  BurpGrpc.proto.BurpApiGrpc.httpResGroup getHttpResGroup();
  /**
   * <code>.BurpMorePossibilityApi.httpResGroup httpResGroup = 4;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.httpResGroupOrBuilder getHttpResGroupOrBuilder();
}
