// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface httpEditorKeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.httpEditorKeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 键
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.ByteData key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <pre>
   * 键
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.ByteData key = 1;</code>
   * @return The key.
   */
  BurpGrpc.proto.BurpApiGrpc.ByteData getKey();
  /**
   * <pre>
   * 键
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.ByteData key = 1;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.ByteDataOrBuilder getKeyOrBuilder();

  /**
   * <pre>
   * 值
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.ByteData value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * 值
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.ByteData value = 2;</code>
   * @return The value.
   */
  BurpGrpc.proto.BurpApiGrpc.ByteData getValue();
  /**
   * <pre>
   * 值
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.ByteData value = 2;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.ByteDataOrBuilder getValueOrBuilder();

  /**
   * <pre>
   * 编辑器名称
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.Str editorName = 3;</code>
   * @return Whether the editorName field is set.
   */
  boolean hasEditorName();
  /**
   * <pre>
   * 编辑器名称
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.Str editorName = 3;</code>
   * @return The editorName.
   */
  BurpGrpc.proto.BurpApiGrpc.Str getEditorName();
  /**
   * <pre>
   * 编辑器名称
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.Str editorName = 3;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.StrOrBuilder getEditorNameOrBuilder();
}
