// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface httpReqDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.httpReqData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *请求包数据
   * </pre>
   *
   * <code>bytes Data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   *请求url
   * </pre>
   *
   * <code>string Url = 2;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   *请求url
   * </pre>
   *
   * <code>string Url = 2;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   *请求体开始下标,如若请求体下标与总长度一致就是没有请求体
   * </pre>
   *
   * <code>int64 BodyIndex = 3;</code>
   * @return The bodyIndex.
   */
  long getBodyIndex();

  /**
   * <pre>
   * http版本
   * </pre>
   *
   * <code>string httpVersion = 4;</code>
   * @return The httpVersion.
   */
  java.lang.String getHttpVersion();
  /**
   * <pre>
   * http版本
   * </pre>
   *
   * <code>string httpVersion = 4;</code>
   * @return The bytes for httpVersion.
   */
  com.google.protobuf.ByteString
      getHttpVersionBytes();

  /**
   * <pre>
   * 目标信息
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.httpReqService httpReqService = 5;</code>
   * @return Whether the httpReqService field is set.
   */
  boolean hasHttpReqService();
  /**
   * <pre>
   * 目标信息
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.httpReqService httpReqService = 5;</code>
   * @return The httpReqService.
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqService getHttpReqService();
  /**
   * <pre>
   * 目标信息
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.httpReqService httpReqService = 5;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqServiceOrBuilder getHttpReqServiceOrBuilder();

  /**
   * <pre>
   * 标记请求体范围
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.Range Range = 6;</code>
   */
  java.util.List<BurpGrpc.proto.BurpApiGrpc.Range> 
      getRangeList();
  /**
   * <pre>
   * 标记请求体范围
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.Range Range = 6;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.Range getRange(int index);
  /**
   * <pre>
   * 标记请求体范围
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.Range Range = 6;</code>
   */
  int getRangeCount();
  /**
   * <pre>
   * 标记请求体范围
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.Range Range = 6;</code>
   */
  java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.RangeOrBuilder> 
      getRangeOrBuilderList();
  /**
   * <pre>
   * 标记请求体范围
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.Range Range = 6;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.RangeOrBuilder getRangeOrBuilder(
      int index);
}
