// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface InsertionPointOffsetsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.InsertionPointOffsets)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 开始下标
   * </pre>
   *
   * <code>int64 StartIndex = 1;</code>
   * @return The startIndex.
   */
  long getStartIndex();

  /**
   * <pre>
   * 结束下标
   * </pre>
   *
   * <code>int64 EndIndex = 2;</code>
   * @return The endIndex.
   */
  long getEndIndex();
}
