// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface IntruderGeneratorDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.IntruderGeneratorData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * http 请求模板
   * </pre>
   *
   * <code>bytes contentData = 1;</code>
   * @return The contentData.
   */
  com.google.protobuf.ByteString getContentData();

  /**
   * <pre>
   * 插入点列表
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.InsertionPointOffsets insertionPointOffsets = 2;</code>
   */
  java.util.List<BurpGrpc.proto.BurpApiGrpc.InsertionPointOffsets> 
      getInsertionPointOffsetsList();
  /**
   * <pre>
   * 插入点列表
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.InsertionPointOffsets insertionPointOffsets = 2;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.InsertionPointOffsets getInsertionPointOffsets(int index);
  /**
   * <pre>
   * 插入点列表
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.InsertionPointOffsets insertionPointOffsets = 2;</code>
   */
  int getInsertionPointOffsetsCount();
  /**
   * <pre>
   * 插入点列表
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.InsertionPointOffsets insertionPointOffsets = 2;</code>
   */
  java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.InsertionPointOffsetsOrBuilder> 
      getInsertionPointOffsetsOrBuilderList();
  /**
   * <pre>
   * 插入点列表
   * </pre>
   *
   * <code>repeated .BurpMorePossibilityApi.InsertionPointOffsets insertionPointOffsets = 2;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.InsertionPointOffsetsOrBuilder getInsertionPointOffsetsOrBuilder(
      int index);

  /**
   * <pre>
   *插入点基值
   * </pre>
   *
   * <code>bytes IntruderInsertionPoint = 3;</code>
   * @return The intruderInsertionPoint.
   */
  com.google.protobuf.ByteString getIntruderInsertionPoint();

  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
