// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 一个上下文菜单项信息
 * </pre>
 *
 * Protobuf type {@code burpApi.MenuInfo}
 */
public final class MenuInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:burpApi.MenuInfo)
    MenuInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MenuInfo.newBuilder() to construct.
  private MenuInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MenuInfo() {
    tarGet_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MenuInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.MenuInfo.class, BurpGrpc.proto.BurpApiGrpc.MenuInfo.Builder.class);
  }

  public static final int TARGET_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tarGet_ = "";
  /**
   * <pre>
   *  string name = 1;  // 名称
   * </pre>
   *
   * <code>string tarGet = 2;</code>
   * @return The tarGet.
   */
  @java.lang.Override
  public java.lang.String getTarGet() {
    java.lang.Object ref = tarGet_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tarGet_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *  string name = 1;  // 名称
   * </pre>
   *
   * <code>string tarGet = 2;</code>
   * @return The bytes for tarGet.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTarGetBytes() {
    java.lang.Object ref = tarGet_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tarGet_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MENU_FIELD_NUMBER = 3;
  private BurpGrpc.proto.BurpApiGrpc.Menu menu_;
  /**
   * <pre>
   * 菜单项
   * </pre>
   *
   * <code>.burpApi.Menu menu = 3;</code>
   * @return Whether the menu field is set.
   */
  @java.lang.Override
  public boolean hasMenu() {
    return menu_ != null;
  }
  /**
   * <pre>
   * 菜单项
   * </pre>
   *
   * <code>.burpApi.Menu menu = 3;</code>
   * @return The menu.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.Menu getMenu() {
    return menu_ == null ? BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance() : menu_;
  }
  /**
   * <pre>
   * 菜单项
   * </pre>
   *
   * <code>.burpApi.Menu menu = 3;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder getMenuOrBuilder() {
    return menu_ == null ? BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance() : menu_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tarGet_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tarGet_);
    }
    if (menu_ != null) {
      output.writeMessage(3, getMenu());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tarGet_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tarGet_);
    }
    if (menu_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMenu());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.MenuInfo)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.MenuInfo other = (BurpGrpc.proto.BurpApiGrpc.MenuInfo) obj;

    if (!getTarGet()
        .equals(other.getTarGet())) return false;
    if (hasMenu() != other.hasMenu()) return false;
    if (hasMenu()) {
      if (!getMenu()
          .equals(other.getMenu())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARGET_FIELD_NUMBER;
    hash = (53 * hash) + getTarGet().hashCode();
    if (hasMenu()) {
      hash = (37 * hash) + MENU_FIELD_NUMBER;
      hash = (53 * hash) + getMenu().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.MenuInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 一个上下文菜单项信息
   * </pre>
   *
   * Protobuf type {@code burpApi.MenuInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:burpApi.MenuInfo)
      BurpGrpc.proto.BurpApiGrpc.MenuInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.MenuInfo.class, BurpGrpc.proto.BurpApiGrpc.MenuInfo.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.MenuInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tarGet_ = "";
      menu_ = null;
      if (menuBuilder_ != null) {
        menuBuilder_.dispose();
        menuBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuInfo_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.MenuInfo getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.MenuInfo.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.MenuInfo build() {
      BurpGrpc.proto.BurpApiGrpc.MenuInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.MenuInfo buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.MenuInfo result = new BurpGrpc.proto.BurpApiGrpc.MenuInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.MenuInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tarGet_ = tarGet_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.menu_ = menuBuilder_ == null
            ? menu_
            : menuBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.MenuInfo) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.MenuInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.MenuInfo other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.MenuInfo.getDefaultInstance()) return this;
      if (!other.getTarGet().isEmpty()) {
        tarGet_ = other.tarGet_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMenu()) {
        mergeMenu(other.getMenu());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              tarGet_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMenuFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tarGet_ = "";
    /**
     * <pre>
     *  string name = 1;  // 名称
     * </pre>
     *
     * <code>string tarGet = 2;</code>
     * @return The tarGet.
     */
    public java.lang.String getTarGet() {
      java.lang.Object ref = tarGet_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tarGet_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *  string name = 1;  // 名称
     * </pre>
     *
     * <code>string tarGet = 2;</code>
     * @return The bytes for tarGet.
     */
    public com.google.protobuf.ByteString
        getTarGetBytes() {
      java.lang.Object ref = tarGet_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tarGet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *  string name = 1;  // 名称
     * </pre>
     *
     * <code>string tarGet = 2;</code>
     * @param value The tarGet to set.
     * @return This builder for chaining.
     */
    public Builder setTarGet(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tarGet_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  string name = 1;  // 名称
     * </pre>
     *
     * <code>string tarGet = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTarGet() {
      tarGet_ = getDefaultInstance().getTarGet();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  string name = 1;  // 名称
     * </pre>
     *
     * <code>string tarGet = 2;</code>
     * @param value The bytes for tarGet to set.
     * @return This builder for chaining.
     */
    public Builder setTarGetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tarGet_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private BurpGrpc.proto.BurpApiGrpc.Menu menu_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.Menu, BurpGrpc.proto.BurpApiGrpc.Menu.Builder, BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder> menuBuilder_;
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     * @return Whether the menu field is set.
     */
    public boolean hasMenu() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     * @return The menu.
     */
    public BurpGrpc.proto.BurpApiGrpc.Menu getMenu() {
      if (menuBuilder_ == null) {
        return menu_ == null ? BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance() : menu_;
      } else {
        return menuBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     */
    public Builder setMenu(BurpGrpc.proto.BurpApiGrpc.Menu value) {
      if (menuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        menu_ = value;
      } else {
        menuBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     */
    public Builder setMenu(
        BurpGrpc.proto.BurpApiGrpc.Menu.Builder builderForValue) {
      if (menuBuilder_ == null) {
        menu_ = builderForValue.build();
      } else {
        menuBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     */
    public Builder mergeMenu(BurpGrpc.proto.BurpApiGrpc.Menu value) {
      if (menuBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          menu_ != null &&
          menu_ != BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance()) {
          getMenuBuilder().mergeFrom(value);
        } else {
          menu_ = value;
        }
      } else {
        menuBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     */
    public Builder clearMenu() {
      bitField0_ = (bitField0_ & ~0x00000002);
      menu_ = null;
      if (menuBuilder_ != null) {
        menuBuilder_.dispose();
        menuBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.Menu.Builder getMenuBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMenuFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder getMenuOrBuilder() {
      if (menuBuilder_ != null) {
        return menuBuilder_.getMessageOrBuilder();
      } else {
        return menu_ == null ?
            BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance() : menu_;
      }
    }
    /**
     * <pre>
     * 菜单项
     * </pre>
     *
     * <code>.burpApi.Menu menu = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.Menu, BurpGrpc.proto.BurpApiGrpc.Menu.Builder, BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder> 
        getMenuFieldBuilder() {
      if (menuBuilder_ == null) {
        menuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.Menu, BurpGrpc.proto.BurpApiGrpc.Menu.Builder, BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder>(
                getMenu(),
                getParentForChildren(),
                isClean());
        menu_ = null;
      }
      return menuBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:burpApi.MenuInfo)
  }

  // @@protoc_insertion_point(class_scope:burpApi.MenuInfo)
  private static final BurpGrpc.proto.BurpApiGrpc.MenuInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.MenuInfo();
  }

  public static BurpGrpc.proto.BurpApiGrpc.MenuInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MenuInfo>
      PARSER = new com.google.protobuf.AbstractParser<MenuInfo>() {
    @java.lang.Override
    public MenuInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MenuInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MenuInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.MenuInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

