// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 菜单项返回 给burp 要做的操作
 * </pre>
 *
 * Protobuf type {@code burpApi.MenuItemsReturn}
 */
public final class MenuItemsReturn extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:burpApi.MenuItemsReturn)
    MenuItemsReturnOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MenuItemsReturn.newBuilder() to construct.
  private MenuItemsReturn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MenuItemsReturn() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MenuItemsReturn();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuItemsReturn_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuItemsReturn_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn.class, BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn.Builder.class);
  }

  public static final int ISREVISEREQ_FIELD_NUMBER = 1;
  private boolean isReviseReq_ = false;
  /**
   * <pre>
   * 修改请求
   * </pre>
   *
   * <code>bool IsReviseReq = 1;</code>
   * @return The isReviseReq.
   */
  @java.lang.Override
  public boolean getIsReviseReq() {
    return isReviseReq_;
  }

  public static final int ISREVISERES_FIELD_NUMBER = 2;
  private boolean isReviseRes_ = false;
  /**
   * <pre>
   * 修改响应
   * </pre>
   *
   * <code>bool IsReviseRes = 2;</code>
   * @return The isReviseRes.
   */
  @java.lang.Override
  public boolean getIsReviseRes() {
    return isReviseRes_;
  }

  public static final int REQDATA_FIELD_NUMBER = 3;
  private BurpGrpc.proto.BurpApiGrpc.httpReqData reqData_;
  /**
   * <pre>
   * 请求数据用于覆盖burp 请求   用于修改 http编辑框
   * </pre>
   *
   * <code>.burpApi.httpReqData ReqData = 3;</code>
   * @return Whether the reqData field is set.
   */
  @java.lang.Override
  public boolean hasReqData() {
    return reqData_ != null;
  }
  /**
   * <pre>
   * 请求数据用于覆盖burp 请求   用于修改 http编辑框
   * </pre>
   *
   * <code>.burpApi.httpReqData ReqData = 3;</code>
   * @return The reqData.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpReqData getReqData() {
    return reqData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqData.getDefaultInstance() : reqData_;
  }
  /**
   * <pre>
   * 请求数据用于覆盖burp 请求   用于修改 http编辑框
   * </pre>
   *
   * <code>.burpApi.httpReqData ReqData = 3;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpReqDataOrBuilder getReqDataOrBuilder() {
    return reqData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqData.getDefaultInstance() : reqData_;
  }

  public static final int RESDATA_FIELD_NUMBER = 4;
  private BurpGrpc.proto.BurpApiGrpc.httpResData resData_;
  /**
   * <pre>
   * 响应数据用于覆盖burp 响应
   * </pre>
   *
   * <code>.burpApi.httpResData ResData = 4;</code>
   * @return Whether the resData field is set.
   */
  @java.lang.Override
  public boolean hasResData() {
    return resData_ != null;
  }
  /**
   * <pre>
   * 响应数据用于覆盖burp 响应
   * </pre>
   *
   * <code>.burpApi.httpResData ResData = 4;</code>
   * @return The resData.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpResData getResData() {
    return resData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : resData_;
  }
  /**
   * <pre>
   * 响应数据用于覆盖burp 响应
   * </pre>
   *
   * <code>.burpApi.httpResData ResData = 4;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder getResDataOrBuilder() {
    return resData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : resData_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isReviseReq_ != false) {
      output.writeBool(1, isReviseReq_);
    }
    if (isReviseRes_ != false) {
      output.writeBool(2, isReviseRes_);
    }
    if (reqData_ != null) {
      output.writeMessage(3, getReqData());
    }
    if (resData_ != null) {
      output.writeMessage(4, getResData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isReviseReq_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isReviseReq_);
    }
    if (isReviseRes_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isReviseRes_);
    }
    if (reqData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getReqData());
    }
    if (resData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getResData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn other = (BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn) obj;

    if (getIsReviseReq()
        != other.getIsReviseReq()) return false;
    if (getIsReviseRes()
        != other.getIsReviseRes()) return false;
    if (hasReqData() != other.hasReqData()) return false;
    if (hasReqData()) {
      if (!getReqData()
          .equals(other.getReqData())) return false;
    }
    if (hasResData() != other.hasResData()) return false;
    if (hasResData()) {
      if (!getResData()
          .equals(other.getResData())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISREVISEREQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsReviseReq());
    hash = (37 * hash) + ISREVISERES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsReviseRes());
    if (hasReqData()) {
      hash = (37 * hash) + REQDATA_FIELD_NUMBER;
      hash = (53 * hash) + getReqData().hashCode();
    }
    if (hasResData()) {
      hash = (37 * hash) + RESDATA_FIELD_NUMBER;
      hash = (53 * hash) + getResData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 菜单项返回 给burp 要做的操作
   * </pre>
   *
   * Protobuf type {@code burpApi.MenuItemsReturn}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:burpApi.MenuItemsReturn)
      BurpGrpc.proto.BurpApiGrpc.MenuItemsReturnOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuItemsReturn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuItemsReturn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn.class, BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isReviseReq_ = false;
      isReviseRes_ = false;
      reqData_ = null;
      if (reqDataBuilder_ != null) {
        reqDataBuilder_.dispose();
        reqDataBuilder_ = null;
      }
      resData_ = null;
      if (resDataBuilder_ != null) {
        resDataBuilder_.dispose();
        resDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_MenuItemsReturn_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn build() {
      BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn result = new BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isReviseReq_ = isReviseReq_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isReviseRes_ = isReviseRes_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reqData_ = reqDataBuilder_ == null
            ? reqData_
            : reqDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.resData_ = resDataBuilder_ == null
            ? resData_
            : resDataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn.getDefaultInstance()) return this;
      if (other.getIsReviseReq() != false) {
        setIsReviseReq(other.getIsReviseReq());
      }
      if (other.getIsReviseRes() != false) {
        setIsReviseRes(other.getIsReviseRes());
      }
      if (other.hasReqData()) {
        mergeReqData(other.getReqData());
      }
      if (other.hasResData()) {
        mergeResData(other.getResData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isReviseReq_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              isReviseRes_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getReqDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getResDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isReviseReq_ ;
    /**
     * <pre>
     * 修改请求
     * </pre>
     *
     * <code>bool IsReviseReq = 1;</code>
     * @return The isReviseReq.
     */
    @java.lang.Override
    public boolean getIsReviseReq() {
      return isReviseReq_;
    }
    /**
     * <pre>
     * 修改请求
     * </pre>
     *
     * <code>bool IsReviseReq = 1;</code>
     * @param value The isReviseReq to set.
     * @return This builder for chaining.
     */
    public Builder setIsReviseReq(boolean value) {

      isReviseReq_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改请求
     * </pre>
     *
     * <code>bool IsReviseReq = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsReviseReq() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isReviseReq_ = false;
      onChanged();
      return this;
    }

    private boolean isReviseRes_ ;
    /**
     * <pre>
     * 修改响应
     * </pre>
     *
     * <code>bool IsReviseRes = 2;</code>
     * @return The isReviseRes.
     */
    @java.lang.Override
    public boolean getIsReviseRes() {
      return isReviseRes_;
    }
    /**
     * <pre>
     * 修改响应
     * </pre>
     *
     * <code>bool IsReviseRes = 2;</code>
     * @param value The isReviseRes to set.
     * @return This builder for chaining.
     */
    public Builder setIsReviseRes(boolean value) {

      isReviseRes_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改响应
     * </pre>
     *
     * <code>bool IsReviseRes = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsReviseRes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isReviseRes_ = false;
      onChanged();
      return this;
    }

    private BurpGrpc.proto.BurpApiGrpc.httpReqData reqData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpReqData, BurpGrpc.proto.BurpApiGrpc.httpReqData.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqDataOrBuilder> reqDataBuilder_;
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     * @return Whether the reqData field is set.
     */
    public boolean hasReqData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     * @return The reqData.
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqData getReqData() {
      if (reqDataBuilder_ == null) {
        return reqData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqData.getDefaultInstance() : reqData_;
      } else {
        return reqDataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     */
    public Builder setReqData(BurpGrpc.proto.BurpApiGrpc.httpReqData value) {
      if (reqDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reqData_ = value;
      } else {
        reqDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     */
    public Builder setReqData(
        BurpGrpc.proto.BurpApiGrpc.httpReqData.Builder builderForValue) {
      if (reqDataBuilder_ == null) {
        reqData_ = builderForValue.build();
      } else {
        reqDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     */
    public Builder mergeReqData(BurpGrpc.proto.BurpApiGrpc.httpReqData value) {
      if (reqDataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          reqData_ != null &&
          reqData_ != BurpGrpc.proto.BurpApiGrpc.httpReqData.getDefaultInstance()) {
          getReqDataBuilder().mergeFrom(value);
        } else {
          reqData_ = value;
        }
      } else {
        reqDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     */
    public Builder clearReqData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      reqData_ = null;
      if (reqDataBuilder_ != null) {
        reqDataBuilder_.dispose();
        reqDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqData.Builder getReqDataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getReqDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqDataOrBuilder getReqDataOrBuilder() {
      if (reqDataBuilder_ != null) {
        return reqDataBuilder_.getMessageOrBuilder();
      } else {
        return reqData_ == null ?
            BurpGrpc.proto.BurpApiGrpc.httpReqData.getDefaultInstance() : reqData_;
      }
    }
    /**
     * <pre>
     * 请求数据用于覆盖burp 请求   用于修改 http编辑框
     * </pre>
     *
     * <code>.burpApi.httpReqData ReqData = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpReqData, BurpGrpc.proto.BurpApiGrpc.httpReqData.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqDataOrBuilder> 
        getReqDataFieldBuilder() {
      if (reqDataBuilder_ == null) {
        reqDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.httpReqData, BurpGrpc.proto.BurpApiGrpc.httpReqData.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqDataOrBuilder>(
                getReqData(),
                getParentForChildren(),
                isClean());
        reqData_ = null;
      }
      return reqDataBuilder_;
    }

    private BurpGrpc.proto.BurpApiGrpc.httpResData resData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpResData, BurpGrpc.proto.BurpApiGrpc.httpResData.Builder, BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder> resDataBuilder_;
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     * @return Whether the resData field is set.
     */
    public boolean hasResData() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     * @return The resData.
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResData getResData() {
      if (resDataBuilder_ == null) {
        return resData_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : resData_;
      } else {
        return resDataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     */
    public Builder setResData(BurpGrpc.proto.BurpApiGrpc.httpResData value) {
      if (resDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resData_ = value;
      } else {
        resDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     */
    public Builder setResData(
        BurpGrpc.proto.BurpApiGrpc.httpResData.Builder builderForValue) {
      if (resDataBuilder_ == null) {
        resData_ = builderForValue.build();
      } else {
        resDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     */
    public Builder mergeResData(BurpGrpc.proto.BurpApiGrpc.httpResData value) {
      if (resDataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          resData_ != null &&
          resData_ != BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance()) {
          getResDataBuilder().mergeFrom(value);
        } else {
          resData_ = value;
        }
      } else {
        resDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     */
    public Builder clearResData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      resData_ = null;
      if (resDataBuilder_ != null) {
        resDataBuilder_.dispose();
        resDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResData.Builder getResDataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getResDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder getResDataOrBuilder() {
      if (resDataBuilder_ != null) {
        return resDataBuilder_.getMessageOrBuilder();
      } else {
        return resData_ == null ?
            BurpGrpc.proto.BurpApiGrpc.httpResData.getDefaultInstance() : resData_;
      }
    }
    /**
     * <pre>
     * 响应数据用于覆盖burp 响应
     * </pre>
     *
     * <code>.burpApi.httpResData ResData = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpResData, BurpGrpc.proto.BurpApiGrpc.httpResData.Builder, BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder> 
        getResDataFieldBuilder() {
      if (resDataBuilder_ == null) {
        resDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.httpResData, BurpGrpc.proto.BurpApiGrpc.httpResData.Builder, BurpGrpc.proto.BurpApiGrpc.httpResDataOrBuilder>(
                getResData(),
                getParentForChildren(),
                isClean());
        resData_ = null;
      }
      return resDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:burpApi.MenuItemsReturn)
  }

  // @@protoc_insertion_point(class_scope:burpApi.MenuItemsReturn)
  private static final BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn();
  }

  public static BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MenuItemsReturn>
      PARSER = new com.google.protobuf.AbstractParser<MenuItemsReturn>() {
    @java.lang.Override
    public MenuItemsReturn parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MenuItemsReturn> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MenuItemsReturn> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.MenuItemsReturn getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

