// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 菜单 菜单下可包含多个菜单和菜单项
 * </pre>
 *
 * Protobuf type {@code BurpMorePossibilityApi.Menu}
 */
public final class Menu extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BurpMorePossibilityApi.Menu)
    MenuOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Menu.newBuilder() to construct.
  private Menu(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Menu() {
    name_ = "";
    menuList_ = java.util.Collections.emptyList();
    menuItemList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Menu();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_Menu_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_Menu_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.Menu.class, BurpGrpc.proto.BurpApiGrpc.Menu.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MENULIST_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<BurpGrpc.proto.BurpApiGrpc.Menu> menuList_;
  /**
   * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
   */
  @java.lang.Override
  public java.util.List<BurpGrpc.proto.BurpApiGrpc.Menu> getMenuListList() {
    return menuList_;
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder> 
      getMenuListOrBuilderList() {
    return menuList_;
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
   */
  @java.lang.Override
  public int getMenuListCount() {
    return menuList_.size();
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.Menu getMenuList(int index) {
    return menuList_.get(index);
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder getMenuListOrBuilder(
      int index) {
    return menuList_.get(index);
  }

  public static final int MENUITEMLIST_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<BurpGrpc.proto.BurpApiGrpc.MenuItem> menuItemList_;
  /**
   * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<BurpGrpc.proto.BurpApiGrpc.MenuItem> getMenuItemListList() {
    return menuItemList_;
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.MenuItemOrBuilder> 
      getMenuItemListOrBuilderList() {
    return menuItemList_;
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
   */
  @java.lang.Override
  public int getMenuItemListCount() {
    return menuItemList_.size();
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.MenuItem getMenuItemList(int index) {
    return menuItemList_.get(index);
  }
  /**
   * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.MenuItemOrBuilder getMenuItemListOrBuilder(
      int index) {
    return menuItemList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < menuList_.size(); i++) {
      output.writeMessage(2, menuList_.get(i));
    }
    for (int i = 0; i < menuItemList_.size(); i++) {
      output.writeMessage(3, menuItemList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < menuList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, menuList_.get(i));
    }
    for (int i = 0; i < menuItemList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, menuItemList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.Menu)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.Menu other = (BurpGrpc.proto.BurpApiGrpc.Menu) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getMenuListList()
        .equals(other.getMenuListList())) return false;
    if (!getMenuItemListList()
        .equals(other.getMenuItemListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getMenuListCount() > 0) {
      hash = (37 * hash) + MENULIST_FIELD_NUMBER;
      hash = (53 * hash) + getMenuListList().hashCode();
    }
    if (getMenuItemListCount() > 0) {
      hash = (37 * hash) + MENUITEMLIST_FIELD_NUMBER;
      hash = (53 * hash) + getMenuItemListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static BurpGrpc.proto.BurpApiGrpc.Menu parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static BurpGrpc.proto.BurpApiGrpc.Menu parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.Menu parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.Menu prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 菜单 菜单下可包含多个菜单和菜单项
   * </pre>
   *
   * Protobuf type {@code BurpMorePossibilityApi.Menu}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BurpMorePossibilityApi.Menu)
      BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_Menu_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_Menu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.Menu.class, BurpGrpc.proto.BurpApiGrpc.Menu.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.Menu.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      if (menuListBuilder_ == null) {
        menuList_ = java.util.Collections.emptyList();
      } else {
        menuList_ = null;
        menuListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (menuItemListBuilder_ == null) {
        menuItemList_ = java.util.Collections.emptyList();
      } else {
        menuItemList_ = null;
        menuItemListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_BurpMorePossibilityApi_Menu_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.Menu getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.Menu build() {
      BurpGrpc.proto.BurpApiGrpc.Menu result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.Menu buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.Menu result = new BurpGrpc.proto.BurpApiGrpc.Menu(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(BurpGrpc.proto.BurpApiGrpc.Menu result) {
      if (menuListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          menuList_ = java.util.Collections.unmodifiableList(menuList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.menuList_ = menuList_;
      } else {
        result.menuList_ = menuListBuilder_.build();
      }
      if (menuItemListBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          menuItemList_ = java.util.Collections.unmodifiableList(menuItemList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.menuItemList_ = menuItemList_;
      } else {
        result.menuItemList_ = menuItemListBuilder_.build();
      }
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.Menu result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.Menu) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.Menu)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.Menu other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (menuListBuilder_ == null) {
        if (!other.menuList_.isEmpty()) {
          if (menuList_.isEmpty()) {
            menuList_ = other.menuList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMenuListIsMutable();
            menuList_.addAll(other.menuList_);
          }
          onChanged();
        }
      } else {
        if (!other.menuList_.isEmpty()) {
          if (menuListBuilder_.isEmpty()) {
            menuListBuilder_.dispose();
            menuListBuilder_ = null;
            menuList_ = other.menuList_;
            bitField0_ = (bitField0_ & ~0x00000002);
            menuListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMenuListFieldBuilder() : null;
          } else {
            menuListBuilder_.addAllMessages(other.menuList_);
          }
        }
      }
      if (menuItemListBuilder_ == null) {
        if (!other.menuItemList_.isEmpty()) {
          if (menuItemList_.isEmpty()) {
            menuItemList_ = other.menuItemList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMenuItemListIsMutable();
            menuItemList_.addAll(other.menuItemList_);
          }
          onChanged();
        }
      } else {
        if (!other.menuItemList_.isEmpty()) {
          if (menuItemListBuilder_.isEmpty()) {
            menuItemListBuilder_.dispose();
            menuItemListBuilder_ = null;
            menuItemList_ = other.menuItemList_;
            bitField0_ = (bitField0_ & ~0x00000004);
            menuItemListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMenuItemListFieldBuilder() : null;
          } else {
            menuItemListBuilder_.addAllMessages(other.menuItemList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              BurpGrpc.proto.BurpApiGrpc.Menu m =
                  input.readMessage(
                      BurpGrpc.proto.BurpApiGrpc.Menu.parser(),
                      extensionRegistry);
              if (menuListBuilder_ == null) {
                ensureMenuListIsMutable();
                menuList_.add(m);
              } else {
                menuListBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              BurpGrpc.proto.BurpApiGrpc.MenuItem m =
                  input.readMessage(
                      BurpGrpc.proto.BurpApiGrpc.MenuItem.parser(),
                      extensionRegistry);
              if (menuItemListBuilder_ == null) {
                ensureMenuItemListIsMutable();
                menuItemList_.add(m);
              } else {
                menuItemListBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<BurpGrpc.proto.BurpApiGrpc.Menu> menuList_ =
      java.util.Collections.emptyList();
    private void ensureMenuListIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        menuList_ = new java.util.ArrayList<BurpGrpc.proto.BurpApiGrpc.Menu>(menuList_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.Menu, BurpGrpc.proto.BurpApiGrpc.Menu.Builder, BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder> menuListBuilder_;

    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public java.util.List<BurpGrpc.proto.BurpApiGrpc.Menu> getMenuListList() {
      if (menuListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(menuList_);
      } else {
        return menuListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public int getMenuListCount() {
      if (menuListBuilder_ == null) {
        return menuList_.size();
      } else {
        return menuListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.Menu getMenuList(int index) {
      if (menuListBuilder_ == null) {
        return menuList_.get(index);
      } else {
        return menuListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder setMenuList(
        int index, BurpGrpc.proto.BurpApiGrpc.Menu value) {
      if (menuListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuListIsMutable();
        menuList_.set(index, value);
        onChanged();
      } else {
        menuListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder setMenuList(
        int index, BurpGrpc.proto.BurpApiGrpc.Menu.Builder builderForValue) {
      if (menuListBuilder_ == null) {
        ensureMenuListIsMutable();
        menuList_.set(index, builderForValue.build());
        onChanged();
      } else {
        menuListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder addMenuList(BurpGrpc.proto.BurpApiGrpc.Menu value) {
      if (menuListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuListIsMutable();
        menuList_.add(value);
        onChanged();
      } else {
        menuListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder addMenuList(
        int index, BurpGrpc.proto.BurpApiGrpc.Menu value) {
      if (menuListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuListIsMutable();
        menuList_.add(index, value);
        onChanged();
      } else {
        menuListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder addMenuList(
        BurpGrpc.proto.BurpApiGrpc.Menu.Builder builderForValue) {
      if (menuListBuilder_ == null) {
        ensureMenuListIsMutable();
        menuList_.add(builderForValue.build());
        onChanged();
      } else {
        menuListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder addMenuList(
        int index, BurpGrpc.proto.BurpApiGrpc.Menu.Builder builderForValue) {
      if (menuListBuilder_ == null) {
        ensureMenuListIsMutable();
        menuList_.add(index, builderForValue.build());
        onChanged();
      } else {
        menuListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder addAllMenuList(
        java.lang.Iterable<? extends BurpGrpc.proto.BurpApiGrpc.Menu> values) {
      if (menuListBuilder_ == null) {
        ensureMenuListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, menuList_);
        onChanged();
      } else {
        menuListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder clearMenuList() {
      if (menuListBuilder_ == null) {
        menuList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        menuListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public Builder removeMenuList(int index) {
      if (menuListBuilder_ == null) {
        ensureMenuListIsMutable();
        menuList_.remove(index);
        onChanged();
      } else {
        menuListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.Menu.Builder getMenuListBuilder(
        int index) {
      return getMenuListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder getMenuListOrBuilder(
        int index) {
      if (menuListBuilder_ == null) {
        return menuList_.get(index);  } else {
        return menuListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder> 
         getMenuListOrBuilderList() {
      if (menuListBuilder_ != null) {
        return menuListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(menuList_);
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.Menu.Builder addMenuListBuilder() {
      return getMenuListFieldBuilder().addBuilder(
          BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance());
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.Menu.Builder addMenuListBuilder(
        int index) {
      return getMenuListFieldBuilder().addBuilder(
          index, BurpGrpc.proto.BurpApiGrpc.Menu.getDefaultInstance());
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.Menu menuList = 2;</code>
     */
    public java.util.List<BurpGrpc.proto.BurpApiGrpc.Menu.Builder> 
         getMenuListBuilderList() {
      return getMenuListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.Menu, BurpGrpc.proto.BurpApiGrpc.Menu.Builder, BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder> 
        getMenuListFieldBuilder() {
      if (menuListBuilder_ == null) {
        menuListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.Menu, BurpGrpc.proto.BurpApiGrpc.Menu.Builder, BurpGrpc.proto.BurpApiGrpc.MenuOrBuilder>(
                menuList_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        menuList_ = null;
      }
      return menuListBuilder_;
    }

    private java.util.List<BurpGrpc.proto.BurpApiGrpc.MenuItem> menuItemList_ =
      java.util.Collections.emptyList();
    private void ensureMenuItemListIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        menuItemList_ = new java.util.ArrayList<BurpGrpc.proto.BurpApiGrpc.MenuItem>(menuItemList_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.MenuItem, BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder, BurpGrpc.proto.BurpApiGrpc.MenuItemOrBuilder> menuItemListBuilder_;

    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public java.util.List<BurpGrpc.proto.BurpApiGrpc.MenuItem> getMenuItemListList() {
      if (menuItemListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(menuItemList_);
      } else {
        return menuItemListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public int getMenuItemListCount() {
      if (menuItemListBuilder_ == null) {
        return menuItemList_.size();
      } else {
        return menuItemListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.MenuItem getMenuItemList(int index) {
      if (menuItemListBuilder_ == null) {
        return menuItemList_.get(index);
      } else {
        return menuItemListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder setMenuItemList(
        int index, BurpGrpc.proto.BurpApiGrpc.MenuItem value) {
      if (menuItemListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuItemListIsMutable();
        menuItemList_.set(index, value);
        onChanged();
      } else {
        menuItemListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder setMenuItemList(
        int index, BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder builderForValue) {
      if (menuItemListBuilder_ == null) {
        ensureMenuItemListIsMutable();
        menuItemList_.set(index, builderForValue.build());
        onChanged();
      } else {
        menuItemListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder addMenuItemList(BurpGrpc.proto.BurpApiGrpc.MenuItem value) {
      if (menuItemListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuItemListIsMutable();
        menuItemList_.add(value);
        onChanged();
      } else {
        menuItemListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder addMenuItemList(
        int index, BurpGrpc.proto.BurpApiGrpc.MenuItem value) {
      if (menuItemListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMenuItemListIsMutable();
        menuItemList_.add(index, value);
        onChanged();
      } else {
        menuItemListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder addMenuItemList(
        BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder builderForValue) {
      if (menuItemListBuilder_ == null) {
        ensureMenuItemListIsMutable();
        menuItemList_.add(builderForValue.build());
        onChanged();
      } else {
        menuItemListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder addMenuItemList(
        int index, BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder builderForValue) {
      if (menuItemListBuilder_ == null) {
        ensureMenuItemListIsMutable();
        menuItemList_.add(index, builderForValue.build());
        onChanged();
      } else {
        menuItemListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder addAllMenuItemList(
        java.lang.Iterable<? extends BurpGrpc.proto.BurpApiGrpc.MenuItem> values) {
      if (menuItemListBuilder_ == null) {
        ensureMenuItemListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, menuItemList_);
        onChanged();
      } else {
        menuItemListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder clearMenuItemList() {
      if (menuItemListBuilder_ == null) {
        menuItemList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        menuItemListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public Builder removeMenuItemList(int index) {
      if (menuItemListBuilder_ == null) {
        ensureMenuItemListIsMutable();
        menuItemList_.remove(index);
        onChanged();
      } else {
        menuItemListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder getMenuItemListBuilder(
        int index) {
      return getMenuItemListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.MenuItemOrBuilder getMenuItemListOrBuilder(
        int index) {
      if (menuItemListBuilder_ == null) {
        return menuItemList_.get(index);  } else {
        return menuItemListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.MenuItemOrBuilder> 
         getMenuItemListOrBuilderList() {
      if (menuItemListBuilder_ != null) {
        return menuItemListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(menuItemList_);
      }
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder addMenuItemListBuilder() {
      return getMenuItemListFieldBuilder().addBuilder(
          BurpGrpc.proto.BurpApiGrpc.MenuItem.getDefaultInstance());
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder addMenuItemListBuilder(
        int index) {
      return getMenuItemListFieldBuilder().addBuilder(
          index, BurpGrpc.proto.BurpApiGrpc.MenuItem.getDefaultInstance());
    }
    /**
     * <code>repeated .BurpMorePossibilityApi.MenuItem menuItemList = 3;</code>
     */
    public java.util.List<BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder> 
         getMenuItemListBuilderList() {
      return getMenuItemListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.MenuItem, BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder, BurpGrpc.proto.BurpApiGrpc.MenuItemOrBuilder> 
        getMenuItemListFieldBuilder() {
      if (menuItemListBuilder_ == null) {
        menuItemListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.MenuItem, BurpGrpc.proto.BurpApiGrpc.MenuItem.Builder, BurpGrpc.proto.BurpApiGrpc.MenuItemOrBuilder>(
                menuItemList_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        menuItemList_ = null;
      }
      return menuItemListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BurpMorePossibilityApi.Menu)
  }

  // @@protoc_insertion_point(class_scope:BurpMorePossibilityApi.Menu)
  private static final BurpGrpc.proto.BurpApiGrpc.Menu DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.Menu();
  }

  public static BurpGrpc.proto.BurpApiGrpc.Menu getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Menu>
      PARSER = new com.google.protobuf.AbstractParser<Menu>() {
    @java.lang.Override
    public Menu parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Menu> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Menu> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.Menu getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

