// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 收到代理响应的操作
 * </pre>
 *
 * Protobuf type {@code burpApi.ProxyResponseAction}
 */
public final class ProxyResponseAction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:burpApi.ProxyResponseAction)
    ProxyResponseActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProxyResponseAction.newBuilder() to construct.
  private ProxyResponseAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProxyResponseAction() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProxyResponseAction();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyResponseAction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyResponseAction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction.class, BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction.Builder.class);
  }

  public static final int CONTINUE_FIELD_NUMBER = 1;
  private boolean continue_ = false;
  /**
   * <pre>
   * 继续不做任何处理
   * </pre>
   *
   * <code>bool continue = 1;</code>
   * @return The continue.
   */
  @java.lang.Override
  public boolean getContinue() {
    return continue_;
  }

  public static final int DROP_FIELD_NUMBER = 2;
  private boolean drop_ = false;
  /**
   * <pre>
   * 丢弃响应
   * </pre>
   *
   * <code>bool drop = 2;</code>
   * @return The drop.
   */
  @java.lang.Override
  public boolean getDrop() {
    return drop_;
  }

  public static final int ISREVISERES_FIELD_NUMBER = 3;
  private boolean isReviseRes_ = false;
  /**
   * <pre>
   * 修改响应
   * </pre>
   *
   * <code>bool isReviseRes = 3;</code>
   * @return The isReviseRes.
   */
  @java.lang.Override
  public boolean getIsReviseRes() {
    return isReviseRes_;
  }

  public static final int ISINTERCEPT_FIELD_NUMBER = 4;
  private boolean isIntercept_ = false;
  /**
   * <pre>
   * 是否拦截  无论是否修改都要返回数据也就是httpReqData 字段
   * </pre>
   *
   * <code>bool isIntercept = 4;</code>
   * @return The isIntercept.
   */
  @java.lang.Override
  public boolean getIsIntercept() {
    return isIntercept_;
  }

  public static final int HTTPRESGROUP_FIELD_NUMBER = 5;
  private BurpGrpc.proto.BurpApiGrpc.httpResGroup httpResGroup_;
  /**
   * <pre>
   *  annotationsText annotation = 5 ; // 注解
   *  httpResData res = 6; // 修改响应
   * </pre>
   *
   * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
   * @return Whether the httpResGroup field is set.
   */
  @java.lang.Override
  public boolean hasHttpResGroup() {
    return httpResGroup_ != null;
  }
  /**
   * <pre>
   *  annotationsText annotation = 5 ; // 注解
   *  httpResData res = 6; // 修改响应
   * </pre>
   *
   * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
   * @return The httpResGroup.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpResGroup getHttpResGroup() {
    return httpResGroup_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResGroup.getDefaultInstance() : httpResGroup_;
  }
  /**
   * <pre>
   *  annotationsText annotation = 5 ; // 注解
   *  httpResData res = 6; // 修改响应
   * </pre>
   *
   * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpResGroupOrBuilder getHttpResGroupOrBuilder() {
    return httpResGroup_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResGroup.getDefaultInstance() : httpResGroup_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (continue_ != false) {
      output.writeBool(1, continue_);
    }
    if (drop_ != false) {
      output.writeBool(2, drop_);
    }
    if (isReviseRes_ != false) {
      output.writeBool(3, isReviseRes_);
    }
    if (isIntercept_ != false) {
      output.writeBool(4, isIntercept_);
    }
    if (httpResGroup_ != null) {
      output.writeMessage(5, getHttpResGroup());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (continue_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, continue_);
    }
    if (drop_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, drop_);
    }
    if (isReviseRes_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isReviseRes_);
    }
    if (isIntercept_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isIntercept_);
    }
    if (httpResGroup_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getHttpResGroup());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction other = (BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction) obj;

    if (getContinue()
        != other.getContinue()) return false;
    if (getDrop()
        != other.getDrop()) return false;
    if (getIsReviseRes()
        != other.getIsReviseRes()) return false;
    if (getIsIntercept()
        != other.getIsIntercept()) return false;
    if (hasHttpResGroup() != other.hasHttpResGroup()) return false;
    if (hasHttpResGroup()) {
      if (!getHttpResGroup()
          .equals(other.getHttpResGroup())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTINUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getContinue());
    hash = (37 * hash) + DROP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDrop());
    hash = (37 * hash) + ISREVISERES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsReviseRes());
    hash = (37 * hash) + ISINTERCEPT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsIntercept());
    if (hasHttpResGroup()) {
      hash = (37 * hash) + HTTPRESGROUP_FIELD_NUMBER;
      hash = (53 * hash) + getHttpResGroup().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 收到代理响应的操作
   * </pre>
   *
   * Protobuf type {@code burpApi.ProxyResponseAction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:burpApi.ProxyResponseAction)
      BurpGrpc.proto.BurpApiGrpc.ProxyResponseActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyResponseAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyResponseAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction.class, BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      continue_ = false;
      drop_ = false;
      isReviseRes_ = false;
      isIntercept_ = false;
      httpResGroup_ = null;
      if (httpResGroupBuilder_ != null) {
        httpResGroupBuilder_.dispose();
        httpResGroupBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyResponseAction_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction build() {
      BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction result = new BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.continue_ = continue_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.drop_ = drop_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isReviseRes_ = isReviseRes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isIntercept_ = isIntercept_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.httpResGroup_ = httpResGroupBuilder_ == null
            ? httpResGroup_
            : httpResGroupBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction.getDefaultInstance()) return this;
      if (other.getContinue() != false) {
        setContinue(other.getContinue());
      }
      if (other.getDrop() != false) {
        setDrop(other.getDrop());
      }
      if (other.getIsReviseRes() != false) {
        setIsReviseRes(other.getIsReviseRes());
      }
      if (other.getIsIntercept() != false) {
        setIsIntercept(other.getIsIntercept());
      }
      if (other.hasHttpResGroup()) {
        mergeHttpResGroup(other.getHttpResGroup());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              continue_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              drop_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              isReviseRes_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isIntercept_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getHttpResGroupFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean continue_ ;
    /**
     * <pre>
     * 继续不做任何处理
     * </pre>
     *
     * <code>bool continue = 1;</code>
     * @return The continue.
     */
    @java.lang.Override
    public boolean getContinue() {
      return continue_;
    }
    /**
     * <pre>
     * 继续不做任何处理
     * </pre>
     *
     * <code>bool continue = 1;</code>
     * @param value The continue to set.
     * @return This builder for chaining.
     */
    public Builder setContinue(boolean value) {

      continue_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 继续不做任何处理
     * </pre>
     *
     * <code>bool continue = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContinue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      continue_ = false;
      onChanged();
      return this;
    }

    private boolean drop_ ;
    /**
     * <pre>
     * 丢弃响应
     * </pre>
     *
     * <code>bool drop = 2;</code>
     * @return The drop.
     */
    @java.lang.Override
    public boolean getDrop() {
      return drop_;
    }
    /**
     * <pre>
     * 丢弃响应
     * </pre>
     *
     * <code>bool drop = 2;</code>
     * @param value The drop to set.
     * @return This builder for chaining.
     */
    public Builder setDrop(boolean value) {

      drop_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 丢弃响应
     * </pre>
     *
     * <code>bool drop = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDrop() {
      bitField0_ = (bitField0_ & ~0x00000002);
      drop_ = false;
      onChanged();
      return this;
    }

    private boolean isReviseRes_ ;
    /**
     * <pre>
     * 修改响应
     * </pre>
     *
     * <code>bool isReviseRes = 3;</code>
     * @return The isReviseRes.
     */
    @java.lang.Override
    public boolean getIsReviseRes() {
      return isReviseRes_;
    }
    /**
     * <pre>
     * 修改响应
     * </pre>
     *
     * <code>bool isReviseRes = 3;</code>
     * @param value The isReviseRes to set.
     * @return This builder for chaining.
     */
    public Builder setIsReviseRes(boolean value) {

      isReviseRes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改响应
     * </pre>
     *
     * <code>bool isReviseRes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsReviseRes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isReviseRes_ = false;
      onChanged();
      return this;
    }

    private boolean isIntercept_ ;
    /**
     * <pre>
     * 是否拦截  无论是否修改都要返回数据也就是httpReqData 字段
     * </pre>
     *
     * <code>bool isIntercept = 4;</code>
     * @return The isIntercept.
     */
    @java.lang.Override
    public boolean getIsIntercept() {
      return isIntercept_;
    }
    /**
     * <pre>
     * 是否拦截  无论是否修改都要返回数据也就是httpReqData 字段
     * </pre>
     *
     * <code>bool isIntercept = 4;</code>
     * @param value The isIntercept to set.
     * @return This builder for chaining.
     */
    public Builder setIsIntercept(boolean value) {

      isIntercept_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否拦截  无论是否修改都要返回数据也就是httpReqData 字段
     * </pre>
     *
     * <code>bool isIntercept = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsIntercept() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isIntercept_ = false;
      onChanged();
      return this;
    }

    private BurpGrpc.proto.BurpApiGrpc.httpResGroup httpResGroup_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpResGroup, BurpGrpc.proto.BurpApiGrpc.httpResGroup.Builder, BurpGrpc.proto.BurpApiGrpc.httpResGroupOrBuilder> httpResGroupBuilder_;
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     * @return Whether the httpResGroup field is set.
     */
    public boolean hasHttpResGroup() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     * @return The httpResGroup.
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResGroup getHttpResGroup() {
      if (httpResGroupBuilder_ == null) {
        return httpResGroup_ == null ? BurpGrpc.proto.BurpApiGrpc.httpResGroup.getDefaultInstance() : httpResGroup_;
      } else {
        return httpResGroupBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     */
    public Builder setHttpResGroup(BurpGrpc.proto.BurpApiGrpc.httpResGroup value) {
      if (httpResGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        httpResGroup_ = value;
      } else {
        httpResGroupBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     */
    public Builder setHttpResGroup(
        BurpGrpc.proto.BurpApiGrpc.httpResGroup.Builder builderForValue) {
      if (httpResGroupBuilder_ == null) {
        httpResGroup_ = builderForValue.build();
      } else {
        httpResGroupBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     */
    public Builder mergeHttpResGroup(BurpGrpc.proto.BurpApiGrpc.httpResGroup value) {
      if (httpResGroupBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          httpResGroup_ != null &&
          httpResGroup_ != BurpGrpc.proto.BurpApiGrpc.httpResGroup.getDefaultInstance()) {
          getHttpResGroupBuilder().mergeFrom(value);
        } else {
          httpResGroup_ = value;
        }
      } else {
        httpResGroupBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     */
    public Builder clearHttpResGroup() {
      bitField0_ = (bitField0_ & ~0x00000010);
      httpResGroup_ = null;
      if (httpResGroupBuilder_ != null) {
        httpResGroupBuilder_.dispose();
        httpResGroupBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResGroup.Builder getHttpResGroupBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getHttpResGroupFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpResGroupOrBuilder getHttpResGroupOrBuilder() {
      if (httpResGroupBuilder_ != null) {
        return httpResGroupBuilder_.getMessageOrBuilder();
      } else {
        return httpResGroup_ == null ?
            BurpGrpc.proto.BurpApiGrpc.httpResGroup.getDefaultInstance() : httpResGroup_;
      }
    }
    /**
     * <pre>
     *  annotationsText annotation = 5 ; // 注解
     *  httpResData res = 6; // 修改响应
     * </pre>
     *
     * <code>.burpApi.httpResGroup httpResGroup = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpResGroup, BurpGrpc.proto.BurpApiGrpc.httpResGroup.Builder, BurpGrpc.proto.BurpApiGrpc.httpResGroupOrBuilder> 
        getHttpResGroupFieldBuilder() {
      if (httpResGroupBuilder_ == null) {
        httpResGroupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.httpResGroup, BurpGrpc.proto.BurpApiGrpc.httpResGroup.Builder, BurpGrpc.proto.BurpApiGrpc.httpResGroupOrBuilder>(
                getHttpResGroup(),
                getParentForChildren(),
                isClean());
        httpResGroup_ = null;
      }
      return httpResGroupBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:burpApi.ProxyResponseAction)
  }

  // @@protoc_insertion_point(class_scope:burpApi.ProxyResponseAction)
  private static final BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction();
  }

  public static BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProxyResponseAction>
      PARSER = new com.google.protobuf.AbstractParser<ProxyResponseAction>() {
    @java.lang.Override
    public ProxyResponseAction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProxyResponseAction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProxyResponseAction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.ProxyResponseAction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

