// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 收到代理请求的操作
 * </pre>
 *
 * Protobuf type {@code burpApi.ProxyRequestAction}
 */
public final class ProxyRequestAction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:burpApi.ProxyRequestAction)
    ProxyRequestActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProxyRequestAction.newBuilder() to construct.
  private ProxyRequestAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProxyRequestAction() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProxyRequestAction();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyRequestAction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyRequestAction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction.class, BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction.Builder.class);
  }

  public static final int CONTINUE_FIELD_NUMBER = 1;
  private boolean continue_ = false;
  /**
   * <pre>
   * 继续不做任何处理
   * </pre>
   *
   * <code>bool continue = 1;</code>
   * @return The continue.
   */
  @java.lang.Override
  public boolean getContinue() {
    return continue_;
  }

  public static final int DROP_FIELD_NUMBER = 2;
  private boolean drop_ = false;
  /**
   * <pre>
   * 丢弃请求
   * </pre>
   *
   * <code>bool drop = 2;</code>
   * @return The drop.
   */
  @java.lang.Override
  public boolean getDrop() {
    return drop_;
  }

  public static final int ISREVISEREQ_FIELD_NUMBER = 3;
  private boolean isReviseReq_ = false;
  /**
   * <pre>
   * 修改请求
   * </pre>
   *
   * <code>bool isReviseReq = 3;</code>
   * @return The isReviseReq.
   */
  @java.lang.Override
  public boolean getIsReviseReq() {
    return isReviseReq_;
  }

  public static final int ISINTERCEPT_FIELD_NUMBER = 4;
  private boolean isIntercept_ = false;
  /**
   * <pre>
   * 是否拦截   无论是否修改都要返回数据也就是httpReqData 字段
   * </pre>
   *
   * <code>bool isIntercept = 4;</code>
   * @return The isIntercept.
   */
  @java.lang.Override
  public boolean getIsIntercept() {
    return isIntercept_;
  }

  public static final int HTTPREQGROUP_FIELD_NUMBER = 5;
  private BurpGrpc.proto.BurpApiGrpc.httpReqGroup httpReqGroup_;
  /**
   * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
   * @return Whether the httpReqGroup field is set.
   */
  @java.lang.Override
  public boolean hasHttpReqGroup() {
    return httpReqGroup_ != null;
  }
  /**
   * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
   * @return The httpReqGroup.
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpReqGroup getHttpReqGroup() {
    return httpReqGroup_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqGroup.getDefaultInstance() : httpReqGroup_;
  }
  /**
   * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder getHttpReqGroupOrBuilder() {
    return httpReqGroup_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqGroup.getDefaultInstance() : httpReqGroup_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (continue_ != false) {
      output.writeBool(1, continue_);
    }
    if (drop_ != false) {
      output.writeBool(2, drop_);
    }
    if (isReviseReq_ != false) {
      output.writeBool(3, isReviseReq_);
    }
    if (isIntercept_ != false) {
      output.writeBool(4, isIntercept_);
    }
    if (httpReqGroup_ != null) {
      output.writeMessage(5, getHttpReqGroup());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (continue_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, continue_);
    }
    if (drop_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, drop_);
    }
    if (isReviseReq_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isReviseReq_);
    }
    if (isIntercept_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isIntercept_);
    }
    if (httpReqGroup_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getHttpReqGroup());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction other = (BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction) obj;

    if (getContinue()
        != other.getContinue()) return false;
    if (getDrop()
        != other.getDrop()) return false;
    if (getIsReviseReq()
        != other.getIsReviseReq()) return false;
    if (getIsIntercept()
        != other.getIsIntercept()) return false;
    if (hasHttpReqGroup() != other.hasHttpReqGroup()) return false;
    if (hasHttpReqGroup()) {
      if (!getHttpReqGroup()
          .equals(other.getHttpReqGroup())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTINUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getContinue());
    hash = (37 * hash) + DROP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDrop());
    hash = (37 * hash) + ISREVISEREQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsReviseReq());
    hash = (37 * hash) + ISINTERCEPT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsIntercept());
    if (hasHttpReqGroup()) {
      hash = (37 * hash) + HTTPREQGROUP_FIELD_NUMBER;
      hash = (53 * hash) + getHttpReqGroup().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 收到代理请求的操作
   * </pre>
   *
   * Protobuf type {@code burpApi.ProxyRequestAction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:burpApi.ProxyRequestAction)
      BurpGrpc.proto.BurpApiGrpc.ProxyRequestActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyRequestAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyRequestAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction.class, BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      continue_ = false;
      drop_ = false;
      isReviseReq_ = false;
      isIntercept_ = false;
      httpReqGroup_ = null;
      if (httpReqGroupBuilder_ != null) {
        httpReqGroupBuilder_.dispose();
        httpReqGroupBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_ProxyRequestAction_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction build() {
      BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction result = new BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.continue_ = continue_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.drop_ = drop_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isReviseReq_ = isReviseReq_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isIntercept_ = isIntercept_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.httpReqGroup_ = httpReqGroupBuilder_ == null
            ? httpReqGroup_
            : httpReqGroupBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction.getDefaultInstance()) return this;
      if (other.getContinue() != false) {
        setContinue(other.getContinue());
      }
      if (other.getDrop() != false) {
        setDrop(other.getDrop());
      }
      if (other.getIsReviseReq() != false) {
        setIsReviseReq(other.getIsReviseReq());
      }
      if (other.getIsIntercept() != false) {
        setIsIntercept(other.getIsIntercept());
      }
      if (other.hasHttpReqGroup()) {
        mergeHttpReqGroup(other.getHttpReqGroup());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              continue_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              drop_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              isReviseReq_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isIntercept_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getHttpReqGroupFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean continue_ ;
    /**
     * <pre>
     * 继续不做任何处理
     * </pre>
     *
     * <code>bool continue = 1;</code>
     * @return The continue.
     */
    @java.lang.Override
    public boolean getContinue() {
      return continue_;
    }
    /**
     * <pre>
     * 继续不做任何处理
     * </pre>
     *
     * <code>bool continue = 1;</code>
     * @param value The continue to set.
     * @return This builder for chaining.
     */
    public Builder setContinue(boolean value) {

      continue_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 继续不做任何处理
     * </pre>
     *
     * <code>bool continue = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContinue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      continue_ = false;
      onChanged();
      return this;
    }

    private boolean drop_ ;
    /**
     * <pre>
     * 丢弃请求
     * </pre>
     *
     * <code>bool drop = 2;</code>
     * @return The drop.
     */
    @java.lang.Override
    public boolean getDrop() {
      return drop_;
    }
    /**
     * <pre>
     * 丢弃请求
     * </pre>
     *
     * <code>bool drop = 2;</code>
     * @param value The drop to set.
     * @return This builder for chaining.
     */
    public Builder setDrop(boolean value) {

      drop_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 丢弃请求
     * </pre>
     *
     * <code>bool drop = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDrop() {
      bitField0_ = (bitField0_ & ~0x00000002);
      drop_ = false;
      onChanged();
      return this;
    }

    private boolean isReviseReq_ ;
    /**
     * <pre>
     * 修改请求
     * </pre>
     *
     * <code>bool isReviseReq = 3;</code>
     * @return The isReviseReq.
     */
    @java.lang.Override
    public boolean getIsReviseReq() {
      return isReviseReq_;
    }
    /**
     * <pre>
     * 修改请求
     * </pre>
     *
     * <code>bool isReviseReq = 3;</code>
     * @param value The isReviseReq to set.
     * @return This builder for chaining.
     */
    public Builder setIsReviseReq(boolean value) {

      isReviseReq_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改请求
     * </pre>
     *
     * <code>bool isReviseReq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsReviseReq() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isReviseReq_ = false;
      onChanged();
      return this;
    }

    private boolean isIntercept_ ;
    /**
     * <pre>
     * 是否拦截   无论是否修改都要返回数据也就是httpReqData 字段
     * </pre>
     *
     * <code>bool isIntercept = 4;</code>
     * @return The isIntercept.
     */
    @java.lang.Override
    public boolean getIsIntercept() {
      return isIntercept_;
    }
    /**
     * <pre>
     * 是否拦截   无论是否修改都要返回数据也就是httpReqData 字段
     * </pre>
     *
     * <code>bool isIntercept = 4;</code>
     * @param value The isIntercept to set.
     * @return This builder for chaining.
     */
    public Builder setIsIntercept(boolean value) {

      isIntercept_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否拦截   无论是否修改都要返回数据也就是httpReqData 字段
     * </pre>
     *
     * <code>bool isIntercept = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsIntercept() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isIntercept_ = false;
      onChanged();
      return this;
    }

    private BurpGrpc.proto.BurpApiGrpc.httpReqGroup httpReqGroup_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpReqGroup, BurpGrpc.proto.BurpApiGrpc.httpReqGroup.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder> httpReqGroupBuilder_;
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     * @return Whether the httpReqGroup field is set.
     */
    public boolean hasHttpReqGroup() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     * @return The httpReqGroup.
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqGroup getHttpReqGroup() {
      if (httpReqGroupBuilder_ == null) {
        return httpReqGroup_ == null ? BurpGrpc.proto.BurpApiGrpc.httpReqGroup.getDefaultInstance() : httpReqGroup_;
      } else {
        return httpReqGroupBuilder_.getMessage();
      }
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     */
    public Builder setHttpReqGroup(BurpGrpc.proto.BurpApiGrpc.httpReqGroup value) {
      if (httpReqGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        httpReqGroup_ = value;
      } else {
        httpReqGroupBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     */
    public Builder setHttpReqGroup(
        BurpGrpc.proto.BurpApiGrpc.httpReqGroup.Builder builderForValue) {
      if (httpReqGroupBuilder_ == null) {
        httpReqGroup_ = builderForValue.build();
      } else {
        httpReqGroupBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     */
    public Builder mergeHttpReqGroup(BurpGrpc.proto.BurpApiGrpc.httpReqGroup value) {
      if (httpReqGroupBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          httpReqGroup_ != null &&
          httpReqGroup_ != BurpGrpc.proto.BurpApiGrpc.httpReqGroup.getDefaultInstance()) {
          getHttpReqGroupBuilder().mergeFrom(value);
        } else {
          httpReqGroup_ = value;
        }
      } else {
        httpReqGroupBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     */
    public Builder clearHttpReqGroup() {
      bitField0_ = (bitField0_ & ~0x00000010);
      httpReqGroup_ = null;
      if (httpReqGroupBuilder_ != null) {
        httpReqGroupBuilder_.dispose();
        httpReqGroupBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqGroup.Builder getHttpReqGroupBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getHttpReqGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder getHttpReqGroupOrBuilder() {
      if (httpReqGroupBuilder_ != null) {
        return httpReqGroupBuilder_.getMessageOrBuilder();
      } else {
        return httpReqGroup_ == null ?
            BurpGrpc.proto.BurpApiGrpc.httpReqGroup.getDefaultInstance() : httpReqGroup_;
      }
    }
    /**
     * <code>.burpApi.httpReqGroup httpReqGroup = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.httpReqGroup, BurpGrpc.proto.BurpApiGrpc.httpReqGroup.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder> 
        getHttpReqGroupFieldBuilder() {
      if (httpReqGroupBuilder_ == null) {
        httpReqGroupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.httpReqGroup, BurpGrpc.proto.BurpApiGrpc.httpReqGroup.Builder, BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder>(
                getHttpReqGroup(),
                getParentForChildren(),
                isClean());
        httpReqGroup_ = null;
      }
      return httpReqGroupBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:burpApi.ProxyRequestAction)
  }

  // @@protoc_insertion_point(class_scope:burpApi.ProxyRequestAction)
  private static final BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction();
  }

  public static BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProxyRequestAction>
      PARSER = new com.google.protobuf.AbstractParser<ProxyRequestAction>() {
    @java.lang.Override
    public ProxyRequestAction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProxyRequestAction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProxyRequestAction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.ProxyRequestAction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

