// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface ProxyRequestActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.ProxyRequestAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 继续不做任何处理
   * </pre>
   *
   * <code>bool continue = 1;</code>
   * @return The continue.
   */
  boolean getContinue();

  /**
   * <pre>
   * 丢弃请求
   * </pre>
   *
   * <code>bool drop = 2;</code>
   * @return The drop.
   */
  boolean getDrop();

  /**
   * <pre>
   * 修改请求
   * </pre>
   *
   * <code>bool isReviseReq = 3;</code>
   * @return The isReviseReq.
   */
  boolean getIsReviseReq();

  /**
   * <pre>
   * 是否拦截   无论是否修改都要返回数据也就是httpReqData 字段
   * </pre>
   *
   * <code>bool isIntercept = 4;</code>
   * @return The isIntercept.
   */
  boolean getIsIntercept();

  /**
   * <code>.BurpMorePossibilityApi.httpReqGroup httpReqGroup = 5;</code>
   * @return Whether the httpReqGroup field is set.
   */
  boolean hasHttpReqGroup();
  /**
   * <code>.BurpMorePossibilityApi.httpReqGroup httpReqGroup = 5;</code>
   * @return The httpReqGroup.
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqGroup getHttpReqGroup();
  /**
   * <code>.BurpMorePossibilityApi.httpReqGroup httpReqGroup = 5;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.httpReqGroupOrBuilder getHttpReqGroupOrBuilder();
}
