// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

// Protobuf Java Version: 3.25.1
package BurpGrpc.proto.BurpApiGrpc;

public interface serviceRegisterRoutingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BurpMorePossibilityApi.serviceRegisterRouting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 服务类型
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.serverTypeName serverType = 1;</code>
   * @return The enum numeric value on the wire for serverType.
   */
  int getServerTypeValue();
  /**
   * <pre>
   * 服务类型
   * </pre>
   *
   * <code>.BurpMorePossibilityApi.serverTypeName serverType = 1;</code>
   * @return The serverType.
   */
  BurpGrpc.proto.BurpApiGrpc.serverTypeName getServerType();

  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string Name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string Name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * grpc地址
   * </pre>
   *
   * <code>string GrpcAddress = 3;</code>
   * @return The grpcAddress.
   */
  java.lang.String getGrpcAddress();
  /**
   * <pre>
   * grpc地址
   * </pre>
   *
   * <code>string GrpcAddress = 3;</code>
   * @return The bytes for grpcAddress.
   */
  com.google.protobuf.ByteString
      getGrpcAddressBytes();
}
