// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

public interface serviceRoutingTableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burpApi.serviceRoutingTable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .burpApi.serviceRouting Routing = 1;</code>
   */
  java.util.List<BurpGrpc.proto.BurpApiGrpc.serviceRouting> 
      getRoutingList();
  /**
   * <code>repeated .burpApi.serviceRouting Routing = 1;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.serviceRouting getRouting(int index);
  /**
   * <code>repeated .burpApi.serviceRouting Routing = 1;</code>
   */
  int getRoutingCount();
  /**
   * <code>repeated .burpApi.serviceRouting Routing = 1;</code>
   */
  java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.serviceRoutingOrBuilder> 
      getRoutingOrBuilderList();
  /**
   * <code>repeated .burpApi.serviceRouting Routing = 1;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.serviceRoutingOrBuilder getRoutingOrBuilder(
      int index);
}
