// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

/**
 * <pre>
 * 服务注册列表 用于表示服务列表
 * </pre>
 *
 * Protobuf type {@code burpApi.serviceRegisterRoutingList}
 */
public final class serviceRegisterRoutingList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:burpApi.serviceRegisterRoutingList)
    serviceRegisterRoutingListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use serviceRegisterRoutingList.newBuilder() to construct.
  private serviceRegisterRoutingList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private serviceRegisterRoutingList() {
    serviceList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new serviceRegisterRoutingList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_serviceRegisterRoutingList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_serviceRegisterRoutingList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList.class, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList.Builder.class);
  }

  public static final int SERVICELIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting> serviceList_;
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting> getServiceListList() {
    return serviceList_;
  }
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder> 
      getServiceListOrBuilderList() {
    return serviceList_;
  }
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  @java.lang.Override
  public int getServiceListCount() {
    return serviceList_.size();
  }
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting getServiceList(int index) {
    return serviceList_.get(index);
  }
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder getServiceListOrBuilder(
      int index) {
    return serviceList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < serviceList_.size(); i++) {
      output.writeMessage(1, serviceList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < serviceList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, serviceList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList)) {
      return super.equals(obj);
    }
    BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList other = (BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList) obj;

    if (!getServiceListList()
        .equals(other.getServiceListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServiceListCount() > 0) {
      hash = (37 * hash) + SERVICELIST_FIELD_NUMBER;
      hash = (53 * hash) + getServiceListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 服务注册列表 用于表示服务列表
   * </pre>
   *
   * Protobuf type {@code burpApi.serviceRegisterRoutingList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:burpApi.serviceRegisterRoutingList)
      BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_serviceRegisterRoutingList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_serviceRegisterRoutingList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList.class, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList.Builder.class);
    }

    // Construct using BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (serviceListBuilder_ == null) {
        serviceList_ = java.util.Collections.emptyList();
      } else {
        serviceList_ = null;
        serviceListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BurpGrpc.proto.BurpApiGrpc.BurpApi.internal_static_burpApi_serviceRegisterRoutingList_descriptor;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList getDefaultInstanceForType() {
      return BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList.getDefaultInstance();
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList build() {
      BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList buildPartial() {
      BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList result = new BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList result) {
      if (serviceListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          serviceList_ = java.util.Collections.unmodifiableList(serviceList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.serviceList_ = serviceList_;
      } else {
        result.serviceList_ = serviceListBuilder_.build();
      }
    }

    private void buildPartial0(BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList) {
        return mergeFrom((BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList other) {
      if (other == BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList.getDefaultInstance()) return this;
      if (serviceListBuilder_ == null) {
        if (!other.serviceList_.isEmpty()) {
          if (serviceList_.isEmpty()) {
            serviceList_ = other.serviceList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServiceListIsMutable();
            serviceList_.addAll(other.serviceList_);
          }
          onChanged();
        }
      } else {
        if (!other.serviceList_.isEmpty()) {
          if (serviceListBuilder_.isEmpty()) {
            serviceListBuilder_.dispose();
            serviceListBuilder_ = null;
            serviceList_ = other.serviceList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serviceListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServiceListFieldBuilder() : null;
          } else {
            serviceListBuilder_.addAllMessages(other.serviceList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting m =
                  input.readMessage(
                      BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.parser(),
                      extensionRegistry);
              if (serviceListBuilder_ == null) {
                ensureServiceListIsMutable();
                serviceList_.add(m);
              } else {
                serviceListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting> serviceList_ =
      java.util.Collections.emptyList();
    private void ensureServiceListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        serviceList_ = new java.util.ArrayList<BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting>(serviceList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder> serviceListBuilder_;

    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public java.util.List<BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting> getServiceListList() {
      if (serviceListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(serviceList_);
      } else {
        return serviceListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public int getServiceListCount() {
      if (serviceListBuilder_ == null) {
        return serviceList_.size();
      } else {
        return serviceListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting getServiceList(int index) {
      if (serviceListBuilder_ == null) {
        return serviceList_.get(index);
      } else {
        return serviceListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder setServiceList(
        int index, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting value) {
      if (serviceListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceListIsMutable();
        serviceList_.set(index, value);
        onChanged();
      } else {
        serviceListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder setServiceList(
        int index, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder builderForValue) {
      if (serviceListBuilder_ == null) {
        ensureServiceListIsMutable();
        serviceList_.set(index, builderForValue.build());
        onChanged();
      } else {
        serviceListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder addServiceList(BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting value) {
      if (serviceListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceListIsMutable();
        serviceList_.add(value);
        onChanged();
      } else {
        serviceListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder addServiceList(
        int index, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting value) {
      if (serviceListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceListIsMutable();
        serviceList_.add(index, value);
        onChanged();
      } else {
        serviceListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder addServiceList(
        BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder builderForValue) {
      if (serviceListBuilder_ == null) {
        ensureServiceListIsMutable();
        serviceList_.add(builderForValue.build());
        onChanged();
      } else {
        serviceListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder addServiceList(
        int index, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder builderForValue) {
      if (serviceListBuilder_ == null) {
        ensureServiceListIsMutable();
        serviceList_.add(index, builderForValue.build());
        onChanged();
      } else {
        serviceListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder addAllServiceList(
        java.lang.Iterable<? extends BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting> values) {
      if (serviceListBuilder_ == null) {
        ensureServiceListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serviceList_);
        onChanged();
      } else {
        serviceListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder clearServiceList() {
      if (serviceListBuilder_ == null) {
        serviceList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serviceListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public Builder removeServiceList(int index) {
      if (serviceListBuilder_ == null) {
        ensureServiceListIsMutable();
        serviceList_.remove(index);
        onChanged();
      } else {
        serviceListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder getServiceListBuilder(
        int index) {
      return getServiceListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder getServiceListOrBuilder(
        int index) {
      if (serviceListBuilder_ == null) {
        return serviceList_.get(index);  } else {
        return serviceListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder> 
         getServiceListOrBuilderList() {
      if (serviceListBuilder_ != null) {
        return serviceListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(serviceList_);
      }
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder addServiceListBuilder() {
      return getServiceListFieldBuilder().addBuilder(
          BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.getDefaultInstance());
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder addServiceListBuilder(
        int index) {
      return getServiceListFieldBuilder().addBuilder(
          index, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.getDefaultInstance());
    }
    /**
     * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
     */
    public java.util.List<BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder> 
         getServiceListBuilderList() {
      return getServiceListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder> 
        getServiceListFieldBuilder() {
      if (serviceListBuilder_ == null) {
        serviceListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting.Builder, BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder>(
                serviceList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        serviceList_ = null;
      }
      return serviceListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:burpApi.serviceRegisterRoutingList)
  }

  // @@protoc_insertion_point(class_scope:burpApi.serviceRegisterRoutingList)
  private static final BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList();
  }

  public static BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<serviceRegisterRoutingList>
      PARSER = new com.google.protobuf.AbstractParser<serviceRegisterRoutingList>() {
    @java.lang.Override
    public serviceRegisterRoutingList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<serviceRegisterRoutingList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<serviceRegisterRoutingList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

