// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: burpApi.proto

package BurpGrpc.proto.BurpApiGrpc;

public interface serviceRegisterRoutingListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:burpApi.serviceRegisterRoutingList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  java.util.List<BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting> 
      getServiceListList();
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.serviceRegisterRouting getServiceList(int index);
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  int getServiceListCount();
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  java.util.List<? extends BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder> 
      getServiceListOrBuilderList();
  /**
   * <code>repeated .burpApi.serviceRegisterRouting serviceList = 1;</code>
   */
  BurpGrpc.proto.BurpApiGrpc.serviceRegisterRoutingOrBuilder getServiceListOrBuilder(
      int index);
}
